name = "init-hono-websocket-worker"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[dev]
port = 8787
ip = "0.0.0.0"

[[d1_databases]]
binding = "DB"
database_name = "saki"
database_id = "5df91c9b-5346-4718-8127-4a736fd7b9fb"
migrations_dir = "drizzle"

