import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    nav: {
      story: "Our Story",
      collections: "Collections",
      artisans: "Artisans",
      searchPlaceholder: "Search crafts...",
      languageSelect: "Language Select",
      cart: "Shopping Cart",
      signOut: "Sign Out",
      loginRegister: "Login / Register",
      store: "Store"
    },
    home: {
      heroTitle: "Empowering Indian Artisans Through Digital Commerce",
      heroSubtitle: "Handmade crafts directly to your doorstep with zero middlemen.",
      exploreBtn: "Explore Marketplace",
      becomeSellerBtn: "Become a Seller",
      badgeText: "Preserving Craft • Honoring Hands",
      womenStat: "Women Empowered",
      districtsStat: "Craft Districts",
      productsStat: "Handmade Products",
      paletteTitle: "The Artisan's Palette",
      paletteSub: "Traditional Categories",
      handloomTitle: "Handloom",
      handloomSub: "Threads of heritage",
      potteryTitle: "Pottery",
      potterySub: "Earth moulded by love",
      jewelryTitle: "Jewelry",
      jewelrySub: "Adornments of history",
      paintingsTitle: "Paintings",
      paintingsSub: "Colors of belief",
      embroideryTitle: "Embroidery",
      embroiderySub: "Stitches of storytelling",
      curationSub: "Handpicked Masterpieces",
      curationTitle: "Curation of the Month",
      viewAll: "View All",
      signature: "Signature",
      artisanLabel: "Artisan:",
      spotlightBadge: "The Voices of Craft",
      meetParvati: "Meet Parvati Devi",
      parvatiDesc: "A master weaver from the heart of Madhya Pradesh, Parvati has been perfecting her handloom craft for over 40 years. Her work reaches global collectors through KariGhar, ensuring traditional methods are preserved and her daughters can learn the legacy.",
      parvatiQuote: "\"Every thread holds the story of my ancestors. Digital commerce gives our family a future.\"",
      districtLabel: "District",
      districtVal: "Maheshwar",
      specLabel: "Specialization",
      specVal: "Ajrakh Weave",
      readStoryBtn: "Read Her Story",
      modalTitle: "The Story of Parvati Devi",
      modalSub: "Heritage Weaver, Maheshwar",
      modalPara1: "Parvati Devi is an award-winning craftswoman who occupies the center of her ancestral cottage in Maheshwar. She specializes in handloom silk sarees using gold zari threads and organic natural dyes.",
      modalPara2: "\"Before KariGhar, local traders bought our silk throws for a fraction of their value, delaying payments for months. Today, our silk throws reach art collectors in London, New York, and Tokyo at a fair, sustainable price. The funds go directly to our cooperative bank account within 24 hours.\"",
      modalPara3: "Currently, Parvati is leading a workshop for 12 local girls, sharing her 300-year-old weaving patterns to ensure this beautiful tradition survives into the digital age."
    },
    categories: {
      badge: "Collector Catalog",
      title: "Curation of Craft",
      filters: "Filters",
      clearAll: "Clear All",
      craftType: "Craft Type",
      priceRange: "Price Range",
      upTo: "Up to",
      minRating: "Minimum Rating",
      andUp: " & up",
      allRatings: "All Ratings",
      districtOrigin: "District Origin",
      allDistricts: "All Districts",
      showing: "Showing",
      results: "results",
      for: "for",
      sortBy: "Sort by:",
      mostRecent: "Most Recent",
      priceLowHigh: "Price: Low to High",
      priceHighLow: "Price: High to Low",
      topRated: "Top Rated",
      noMatches: "No matches found",
      noMatchesSub: "Try loosening your filters, price limits, or search terms to find other creations.",
      resetFilters: "Reset Filters",
      signature: "Signature",
      openAssistant: "Open KariGhar Assistant"
    },
    product: {
      notFound: "Creation Not Found",
      notFoundSub: "The handcrafted item you are looking for does not exist in our catalog.",
      backCollections: "Back to Collections",
      addedToCart: "Added to cart!",
      removedWishlist: "Removed from your collector wishlist.",
      addedWishlist: "Added to your collector wishlist!",
      verifiedReview: "Thank you! Your verified collector review has been appended.",
      home: "Home",
      collections: "Collections",
      rating: "Rating",
      collectorReviews: "collector reviews",
      handMadeBhuj: "HAND-THROWN • KUTCH",
      ecoFriendly: "Eco-friendly",
      sustainable: "Sustainable",
      stockStatus: "Stock Status",
      addToCart: "Add to Cart",
      sameCollection: "From the Same Collection",
      whatCollectorsSay: "What our collectors say",
      basedOn: "Based on",
      writeReview: "Write a Review",
      star5: "5 Star",
      star4: "4 Star",
      star3: "3 Star",
      noReviewsYet: "No collector reviews yet. Be the first to share your thoughts on this masterpiece!",
      selectRating: "Select Rating:",
      yourName: "Your Name",
      collectorReviewText: "Collector Review",
      reviewPlaceholder: "Describe the texture, weight, detail, and packaging...",
      submitReview: "Submit Review",
      storyOf: "Story of",
      bhujKutch: "Bhuj, Kutch District",
      closeModal: "Close Modal"
    },
    help: {
      badge: "Artisan Support Hub",
      title: "How can we help you create?",
      uploadTitle: "Product Upload",
      uploadDesc: "Learn how to showcase your craft with high-resolution imagery and ancestral storytelling.",
      pricingTitle: "Pricing Help",
      pricingDesc: "Guidance on fair-trade pricing, computing material costs, and global market positioning.",
      shippingTitle: "Shipping Logistics",
      shippingDesc: "Eco-packaging standards and global shipping partners experienced in delicate art handling.",
      pledgeTitle: "Artisan Pledge",
      pledgeDesc: "Our pledge to 100% transparency, heritage preservation, and immediate bank cooperative pay.",
      communityStory: "Community Story",
      storyTitle: "Bridging Generations through Digital Presence",
      storyDesc: "How Rao's family pottery workshop in a remote Kutch village reached art collectors in Kyoto and San Francisco, doubling their income and ensuring the children can continue their five-generation legacy."
    },
    login: {
      title: "Namaste, Collector",
      sub: "Please log in or register to view your KariGhar dashboard and collector wishlist.",
      signInRegister: "Sign In / Register",
      createAccount: "Create Account",
      welcomeBack: "Welcome Back",
      joinMarketplace: "Join our marketplace to collect or sell.",
      welcomeBackSub: "Welcome back to KariGhar.",
      customer: "Customer",
      sellerArtisan: "Seller Artisan",
      changeProfile: "Change Profile Photo",
      uploadProfile: "Upload Profile Photo",
      fullName: "Full Name",
      enterName: "Enter your name",
      emailAddress: "Email Address",
      password: "Password",
      phoneNumber: "Phone Number",
      creatingAccount: "Creating Account…",
      signingIn: "Signing In…",
      logIn: "Log In",
      orConnect: "OR CONNECT WITH",
      continueGoogle: "Continue with Google",
      alreadyHaveAccount: "Already have an account?",
      dontHaveAccount: "Don't have an account?",
      signUp: "Sign Up"
    },
    profile: {
      partner: "Partner",
      collectorId: "Collector ID",
      accountSettings: "Account Settings",
      editProfile: "Edit Profile",
      saveChanges: "Save Changes",
      cancel: "Cancel",
      welcomeProfile: "Welcome to your KariGhar collector profile. Here you can manage your verified identity details.",
      statusLabel: "Status:",
      activeVerification: "Active Collector Verification",
      wishlistTitle: "Collector Wishlist"
    },
    cart: {
      orderComplete: "Order Complete",
      yourCart: "Your KariGhar Cart",
      cartEmpty: "Your cart is empty.",
      cartEmptySub: "Fill your home with authentic, beautiful, hand-thrown creations from Kutch, Kashmir, and Varanasi.",
      startExploring: "Start Exploring",
      subtotal: "Cart Subtotal",
      shipping: "Eco-Packaging & Shipping",
      total: "Total Amount",
      pledgeText: "🌱 KariGhar Pledge: Shipped in 100% biodegradable husks & hand-drawn wood chips.",
      placeOrder: "Place Order",
      securingTransaction: "Securing Artisan Transaction",
      securingSub: "Connecting directly with rural banking networks to support weavers & potters. Please do not close.",
      orderPlacedSuccess: "Namaste. Order Placed!",
      receiptCreated: "Your collector receipt has been created.",
      preparingPackage: "Master artisans are preparing your unique package. Each item will be carefully nestled in organic wheat-husks and sustainable banana-leaves.",
      profitInfo: "100% of profits are dispatched directly to the weaver/potter's cooperative within 24 hours.",
      returnBtn: "Return to KariGhar",
      free: "Free"
    },
    artisans: {
      liveRooms: "Live Rooms",
      createRoom: "Create Room",
      joinRoom: "Join Room",
      tipOfDay: "Tip of the Day",
      hearthTitle: "KariGhar Community Hearth",
      createRoomSub: "Start a new live session and generate a room code.",
      joinRoomSub: "Enter a 4-digit code to connect to an active room.",
      activeLabel: "Artisans Active",
      liveNow: "Live Now",
      editTopic: "Edit Discussion Topic",
      currentTopic: "Current Discussion Topic",
      save: "Save",
      cancel: "Cancel",
      editTopicBtn: "Edit Topic",
      speaking: "Speaking...",
      youArtisan: "You (Artisan)",
      invite: "Invite",
      muted: "Muted",
      micActive: "Microphone Active",
      youAreSpeaking: "YOU ARE SPEAKING",
      holdToSpeak: "Hold to Speak",
      raiseHand: "Raise Hand",
      leave: "Leave",
      createLiveRoom: "Create Live Room",
      createRoomDesc: "Name your room. A secure 4-digit entry code will be generated automatically for participants.",
      roomName: "Room Name",
      joinLiveRoom: "Join Live Room",
      joinRoomDesc: "Enter the 4-digit code provided by the room host to join their active voice stream."
    },
    seller: {
      overview: "Overview",
      bazaar: "Bazaar (Stock)",
      orders: "Orders",
      earnings: "Earnings",
      sikho: "Sikho (Learn)",
      sisters: "Sisters (Community)",
      welcome: "Welcome, ",
      motto: "\"When we grow together, our village prospers.\"",
      pending: "Pending",
      shipped: "Shipped",
      completed: "Completed",
      ordersTitle: "Customer Orders",
      ordersSub: "Fulfill orders from buyers directly with India Post logistics",
      listenRequest: "Listen Custom Instruction",
      shipPackageBtn: "Ship Package",
      markDeliveredBtn: "Mark Delivered",
      paidDelivered: "Paid & Delivered",
      availablePayout: "Available for Payout",
      linkedBank: "Linked Bank Account",
      lifetimeOverview: "Lifetime Overview",
      withdrawHistory: "Withdrawal & Transaction History",
      withdrawBtn: "Withdraw to Bank",
      sikhoTitle: "Sikho (Learn & Grow)",
      sikhoSub: "Video and audio lessons in your local language to improve photos, packaging, and pricing",
      bazaarTitle: "Bazaar (Your Inventory)",
      bazaarSub: "List products in the global store & manage stock levels",
      addCraftBtn: "Add New Craft",
      stockQuantity: "Stock Quantity",
      availableUnits: "Units Available",
      outOfStock: "Out of Stock",
      bankName: "Bank Name",
      holderName: "Holder Name",
      accNumber: "Account Number",
      ifscCode: "IFSC Code",
      payoutVerify: "Payout Verification",
      connectingSbi: "Connecting SBI Gateway...",
      transSuccessful: "Transfer Successful!",
      sbiRef: "SBI REF ID",
      doneBtn: "Done",
      confirmTrans: "Confirm Transfer",
      recordingDesc: "Recording...",
      voiceDescBtn: "Voice Description",
      listNewCraft: "List New Craft Item",
      instantShow: "Your creation will be shown instantly on the KariGhar customer storefront",
      craftName: "Craft Name",
      categoryLabel: "Category",
      priceLabel: "Price (₹)",
      stockLabel: "Stock Quantity",
      descriptionLabel: "Description",
      selectPicLabel: "Select Craft Picture",
      cancelBtn: "Cancel",
      addCraftSubmit: "Add Craft",
      lessonsHeader: "Sikho (Learn & Grow)",
      lessonsSubText: "Video and audio lessons in your local language to improve photos, packaging, and pricing",
      lessonPhotography: "Lesson 1 • Photography",
      lessonLogistics: "Lesson 2 • Logistics",
      lessonCourier: "Lesson 3 • Courier Support",
      lessonBusiness: "Lesson 4 • Business Basics",
      lowInternet: "Low Internet Mode",
      lowInternetSub: "Streaming audio-only to save mobile data charges. Hindi narration playing.",
      markDone: "Mark Lesson Done"
    },
    sellerOnboarding: {
      welcomeTitle: "Welcome to KariGhar",
      welcomeSubtitle: "\"Apni kaala becho, seedha ghar se.\"",
      newHere: "I am new here",
      haveAccount: "I have an account →",
      voiceWelcome: "\"Welcome. Tap 'I am new here' to start selling your craft.\"",
      browseCustomer: "Browse as a customer instead",
      consumerStore: "Consumer Store",
      namasteSister: "\"Namaste behen, let's start your journey.\"",
      tellName: "Tell us your name",
      fullName: "Full Name",
      placeholderName: "E.g. Radha Devi",
      speakOrType: "Speak clearly into the microphone or type your name using the keyboard.",
      next: "Next →",
      needHelpWatch: "Need help? Watch: How to use KariGhar",
      voiceGuidanceStep1: "Let's create your profile. Please tell your full name.",
      createSecretCode: "Apna secret code banayein",
      rememberCode: "\"Aisa code rakhein jo aapko hamesha yaad rahe\"",
      secretCodeLabel: "Secret Code (Password)",
      placeholderCode: "e.g. 1234",
      aageBadhein: "Aage Badhein →",
      listening: "Main sun rahi hoon...",
      watchTypeCode: "Watch: How to type your code",
      empoweringArtisansDesc: "CRAFT & CODE: EMPOWERING ARTISANS — Learn to Use the Heritage Hearth App!",
      voiceGuidanceStep2: "Ek simple code chuniye jo aapko yaad rahe. Main isse surakshit rakhungi.",
      whereAreYouFrom: "Kahan se hain aap?",
      enterPhoneLocation: "\"Apna phone number aur jagah batayein\"",
      voiceGuidanceStep3: "\"Apna phone number aur shehar chuniye taaki grahak aapko dhoond sakein.\"",
      phoneNumberLabel: "Phone Number",
      stateLabel: "Rajya (State)",
      districtLabel: "Zila (District)",
      selectState: "— Select State —",
      selectDistrict: "— Select District —",
      empoweringArtisansTitle: "CRAFT & CODE: EMPOWERING ARTISANS",
      welcomeBackSister: "\"Welcome back, Sister. Your craft inspires us all.\"",
      enterNamePass: "Please enter your name and password.",
      loginLabel: "Login →"
    },
    chatbot: {
      tooltipText: "Facing any problem?",
      tooltipSub: "Tap me, I'm here to guide you!",
      onlineSupport: "Online & Guided Support",
      assistantName: "KariGhar Assistant",
      inputPlaceholder: "Ask a question...",
      footerBranding: "Preserving Indian Craft • KariGhar Companion",
      introDefault: "Namaste! I am your KariGhar digital companion. How can I help you navigate our artisan marketplace today? ❀",
      introHome: "Welcome to KariGhar! I can guide you through our artisan stories, help you browse handcraft categories, or explain our direct fair-trade model. How can I assist you? ❀",
      introCategories: "Browsing our curation grid? You can filter crafts by specific Indian districts or use the sliding pricing scale to match your budget. Need help finding something unique? ❀",
      introProduct: "This heritage creation is hand-made with regional organic materials! Would you like to review the 3-stage artisanal crafting process or check shipping safety? ❀",
      introSeller: "Namaste Partner! In your Artisan Workspace, you can compute a regional living wage using our Fair-Trade Pricing Tool, generate direct WhatsApp chat links, or record an audio description. Need help? ❀",
      introHelp: "You have reached the Support Hub! I am sync-enabled in Hindi and English. Type any question below or click a quick chip to stream an instant reply! ❀",
      introLogin: "Welcome to our Namaste Authentication panel! You can easily register as a Customer or Seller, upload your profile picture, and enter the mock OTP code '1234' to verify. ❀",
      ackHindi: "नमस्ते! अब मैं हिन्दी में आपकी सहायता के लिए तैयार हूँ। आप अपना प्रश्न पूछ सकते हैं। ❀",
      ackEnglish: "Great! I am now ready to assist you in English (India). How can I help you today? ❀",
      ackKannada: "ನಮಸ್ತೆ! ಈಗ ನಾನು ಕನ್ನಡದಲ್ಲಿ ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧನಾಗಿದ್ದೇನೆ. ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಬಹುದು. ❀",
      errorMsg: "Namaste! I'm having trouble connecting right now. Please try again in a moment, or explore our Help page for FAQs. 🙏",
      chips: {
        livingWage: "Living Wage Calculator",
        whatsapp: "WhatsApp Chat Setup",
        voiceRec: "Voice Recorder Help",
        howOrder: "How to order?",
        directFair: "Direct Fair-Trade?",
        meetArtisans: "Meet Our Artisans",
        fragileShip: "Fragile Shipping",
        loomWeave: "Loom Weaving Process",
        reviewGuide: "Review Guidelines",
        genGuide: "General Website Guide",
        otpVerify: "OTP Verification",
        packagingStd: "Packaging Standards"
      }
    }
  },
  hi: {
    nav: {
      story: "हमारी कहानी",
      collections: "कला संग्रह",
      artisans: "महिला कारीगर",
      searchPlaceholder: "हस्तशिल्प खोजें...",
      languageSelect: "भाषा चुनें",
      cart: "खरीददारी थैला",
      signOut: "लॉग आउट",
      loginRegister: "लॉगिन / पंजीकरण",
      store: "दुकान"
    },
    home: {
      heroTitle: "डिजिटल व्यापार के माध्यम से भारतीय कारीगरों का सशक्तिकरण",
      heroSubtitle: "बिना किसी बिचौलिये के सीधे आपके घर तक पहुँचने वाले हस्तनिर्मित उत्पाद।",
      exploreBtn: "मार्केटप्लेस देखें",
      becomeSellerBtn: "विक्रेता बनें",
      badgeText: "शिल्प का संरक्षण • हाथों का सम्मान",
      womenStat: "महिलाएं सशक्त",
      districtsStat: "कुशलता क्षेत्र",
      productsStat: "हस्तनिर्मित उत्पाद",
      paletteTitle: "कारीगर की कलाकृतियां",
      paletteSub: "पारंपरिक श्रेणियां",
      handloomTitle: "हथकरघा",
      handloomSub: "विरासत के धागे",
      potteryTitle: "मिट्टी के बर्तन",
      potterySub: "प्यार से ढली मिट्टी",
      jewelryTitle: "आभूषण",
      jewelrySub: "इतिहास के आभूषण",
      paintingsTitle: "चित्रकारी",
      paintingsSub: "आस्था के रंग",
      embroideryTitle: "कढ़ाई",
      embroiderySub: "कहानियों के टांके",
      curationSub: "चुनिंदा उत्कृष्ट कृतियां",
      curationTitle: "इस महीने की विशेष प्रस्तुतियां",
      viewAll: "सभी देखें",
      signature: "सिग्नेचर",
      artisanLabel: "कारीगर:",
      spotlightBadge: "शिल्प की आवाज",
      meetParvati: "पार्वती देवी से मिलें",
      parvatiDesc: "मध्य प्रदेश के दिल से एक मास्टर बुनकर, पार्वती पिछले 40 वर्षों से अपने हथकरघा शिल्प को पूरा कर रही हैं। उनका काम कारीघर के माध्यम से वैश्विक संग्राहकों तक पहुंचता है, जिससे यह सुनिश्चित होता है कि पारंपरिक तरीकों को संरक्षित किया जाए और उनकी बेटियां विरासत को सीख सकें।",
      parvatiQuote: "\"हर धागे में मेरे पूर्वजों की कहानी है। डिजिटल व्यापार हमारे परिवार को भविष्य देता है।\"",
      districtLabel: "जिला",
      districtVal: "महेश्वर",
      specLabel: "विशेषज्ञता",
      specVal: "अजरख बुनाई",
      readStoryBtn: "उनकी कहानी पढ़ें",
      modalTitle: "पार्वती देवी की कहानी",
      modalSub: "विरासत बुनकर, महेश्वर",
      modalPara1: "पार्वती देवी एक पुरस्कार विजेता शिल्पकार हैं जो महेश्वर में अपने पैतृक कुटीर के केंद्र में रहती हैं। वह सोने के ज़री धागे और जैविक प्राकृतिक रंगों का उपयोग करके हथकरघा रेशम की साड़ियों में माहिर हैं।",
      modalPara2: "\"कारीघर से पहले, स्थानीय व्यापारी हमारे सिल्क थ्रो को उनके मूल्य के एक अंश पर खरीदते थे, जिससे महीनों तक भुगतान में देरी होती थी। आज, हमारे सिल्क थ्रो लंदन, न्यूयॉर्क और टोक्यो में कला संग्राहकों तक उचित और स्थायी कीमत पर पहुंचते हैं। फंड 24 घंटे के भीतर सीधे हमारे सहकारी बैंक खाते में चले जाते हैं।\"",
      modalPara3: "वर्तमान में, पार्वती 12 स्थानीय लड़कियों के लिए एक कार्यशाला का नेतृत्व कर रही हैं, अपने 300 साल पुराने बुनाई पैटर्न को साझा कर रही हैं ताकि यह सुनिश्चित हो सके कि यह सुंदर परंपरा डिजिटल युग में जीवित रहे।"
    },
    categories: {
      badge: "कलेक्टर सूची",
      title: "शिल्प की कलाकृतियां",
      filters: "फ़िल्टर",
      clearAll: "सभी साफ़ करें",
      craftType: "शिल्प का प्रकार",
      priceRange: "मूल्य सीमा",
      upTo: "तक",
      minRating: "न्यूनतम रेटिंग",
      andUp: " और ऊपर",
      allRatings: "सभी रेटिंग",
      districtOrigin: "उत्पत्ति जिला",
      allDistricts: "सभी जिले",
      showing: "दिखाए जा रहे",
      results: "परिणाम",
      for: "के लिए",
      sortBy: "क्रमबद्ध करें:",
      mostRecent: "नवीनतम",
      priceLowHigh: "मूल्य: कम से अधिक",
      priceHighLow: "मूल्य: अधिक से कम",
      topRated: "उच्चतम रेटिंग",
      noMatches: "कोई मेल नहीं मिला",
      noMatchesSub: "अन्य कृतियों को खोजने के लिए अपने फ़िल्टर, मूल्य सीमा या खोज शब्दों को बदलने का प्रयास करें।",
      resetFilters: "फ़िल्टर रीसेट करें",
      signature: "हस्ताक्षर",
      openAssistant: "कारीघर सहायक खोलें"
    },
    product: {
      notFound: "कृति नहीं मिली",
      notFoundSub: "जिस हस्तनिर्मित वस्तु की आप तलाश कर रहे हैं वह हमारी सूची में नहीं है।",
      backCollections: "संग्रह पर वापस जाएं",
      addedToCart: "कार्ट में जोड़ा गया!",
      removedWishlist: "आपकी कलेक्टर इच्छा सूची से हटा दिया गया।",
      addedWishlist: "आपकी कलेक्टर इच्छा सूची में जोड़ा गया!",
      verifiedReview: "धन्यवाद! आपकी सत्यापित समीक्षा जोड़ दी गई है।",
      home: "होम",
      collections: "संग्रह",
      rating: "रेटिंग",
      collectorReviews: "कलेक्टर समीक्षाएं",
      handMadeBhuj: "हस्तनिर्मित • कच्छ",
      ecoFriendly: "पर्यावरण के अनुकूल",
      sustainable: "सतत",
      stockStatus: "स्टॉक की स्थिति",
      addToCart: "कार्ट में जोड़ें",
      sameCollection: "इसी संग्रह से",
      whatCollectorsSay: "हमारे संग्राहक क्या कहते हैं",
      basedOn: "पर आधारित",
      writeReview: "समीक्षा लिखें",
      star5: "5 स्टार",
      star4: "4 स्टार",
      star3: "3 स्टार",
      noReviewsYet: "अभी तक कोई कलेक्टर समीक्षा नहीं है। इस कृति पर अपने विचार साझा करने वाले पहले व्यक्ति बनें!",
      selectRating: "रेटिंग चुनें:",
      yourName: "आपका नाम",
      collectorReviewText: "कलेक्टर समीक्षा",
      reviewPlaceholder: "बनावट, वजन, विवरण और पैकेजिंग का वर्णन करें...",
      submitReview: "समीक्षा भेजें",
      storyOf: "की कहानी",
      bhujKutch: "भुज, कच्छ जिला",
      closeModal: "मोडल बंद करें"
    },
    help: {
      badge: "कारीगर सहायता केंद्र",
      title: "हम आपकी निर्माण में कैसे मदद कर सकते हैं?",
      uploadTitle: "उत्पाद अपलोड",
      uploadDesc: "उच्च-रिज़ॉल्यूशन इमेजरी और अपनी पारंपरिक कहानी के साथ अपने शिल्प को प्रदर्शित करना सीखें।",
      pricingTitle: "मूल्य निर्धारण सहायता",
      pricingDesc: "उचित-व्यापार मूल्य निर्धारण, सामग्री लागत की गणना, और वैश्विक बाजार स्थिति पर मार्गदर्शन।",
      shippingTitle: "शिपिंग रसद",
      shippingDesc: "नाजुक कला को संभालने में अनुभवी वैश्विक शिपिंग भागीदार और पर्यावरण-पैकेजिंग मानक।",
      pledgeTitle: "कारीगर प्रतिज्ञा",
      pledgeDesc: "100% पारदर्शिता, विरासत संरक्षण, और तत्काल सहकारी बैंक भुगतान के लिए हमारी प्रतिज्ञा।" ,
      communityStory: "सामुदायिक कहानी",
      storyTitle: "डिजिटल उपस्थिति के माध्यम से पीढ़ियों को जोड़ना",
      storyDesc: "कैसे एक सुदूर कच्छ गाँव में राव के पारिवारिक मिट्टी के बर्तनों की कार्यशाला ने क्योटो और सैन फ्रांसिस्को में कला संग्राहकों तक पहुँचकर अपनी आय दोगुनी कर दी और यह सुनिश्चित किया कि उनके बच्चे अपनी पांच पीढ़ियों की विरासत को जारी रख सकें।"
    },
    login: {
      title: "नमस्ते, कलेक्टर",
      sub: "कृपया अपने कारीघर डैशबोर्ड और कलेक्टर इच्छा सूची को देखने के लिए लॉगिन या पंजीकरण करें।",
      signInRegister: "लॉग इन / पंजीकरण",
      createAccount: "खाता बनाएं",
      welcomeBack: "स्वागत है",
      joinMarketplace: "संग्रह करने या बेचने के लिए हमारे बाज़ार से जुड़ें।",
      welcomeBackSub: "कारीघर में आपका स्वागत है।",
      customer: "ग्राहक",
      sellerArtisan: "विक्रेता कारीगर",
      changeProfile: "प्रोफ़ाइल फ़ोटो बदलें",
      uploadProfile: "प्रोफ़ाइल फ़ोटो अपलोड करें",
      fullName: "पूरा नाम",
      enterName: "अपना नाम दर्ज करें",
      emailAddress: "ईमेल पता",
      password: "पासवर्ड",
      phoneNumber: "फ़ोन नंबर",
      creatingAccount: "खाता बनाया जा रहा है...",
      signingIn: "साइन इन किया जा रहा है...",
      logIn: "लॉग इन करें",
      orConnect: "या इसके साथ जुड़ें",
      continueGoogle: "गूगल के साथ जारी रखें",
      alreadyHaveAccount: "पहले से ही एक खाता है?",
      dontHaveAccount: "खाता नहीं है?",
      signUp: "साइन अप करें"
    },
    profile: {
      partner: "साझेदार",
      collectorId: "कलेक्टर आईडी",
      accountSettings: "खाता सेटिंग",
      editProfile: "प्रोफ़ाइल संपादित करें",
      saveChanges: "परिवर्तन सहेजें",
      cancel: "रद्द करें",
      welcomeProfile: "आपके कारीघर कलेक्टर प्रोफ़ाइल में आपका स्वागत है। यहाँ आप अपने सत्यापित पहचान विवरण प्रबंधित कर सकते हैं।",
      statusLabel: "स्थिति:",
      activeVerification: "सक्रिय कलेक्टर सत्यापन",
      wishlistTitle: "कलेक्टर इच्छा सूची"
    },
    cart: {
      orderComplete: "आर्डर पूरा हुआ",
      yourCart: "आपका कारीघर कार्ट",
      cartEmpty: "आपका कार्ट खाली है।",
      cartEmptySub: "कच्छ, कश्मीर और वाराणसी की प्रामाणिक, सुंदर, हस्तनिर्मित कृतियों से अपने घर को सजाएं।",
      startExploring: "अन्वेषण शुरू करें",
      subtotal: "कार्ट उप-योग",
      shipping: "पर्यावरण पैकेजिंग और शिपिंग",
      total: "कुल राशि",
      pledgeText: "🌱 कारीघर प्रतिज्ञा: 100% बायोडिग्रेडेबल भूसी और हस्तनिर्मित लकड़ी के टुकड़ों में भेज दिया गया।",
      placeOrder: "ऑर्डर दें",
      securingTransaction: "कारीगर लेनदेन सुरक्षित करना",
      securingSub: "बुनकरों और कुम्हारों की सहायता के लिए सीधे ग्रामीण बैंकिंग नेटवर्क से जुड़ना। कृपया बंद न करें।",
      orderPlacedSuccess: "नमस्ते। ऑर्डर दे दिया गया है!",
      receiptCreated: "आपकी कलेक्टर रसीद बन गई है।",
      preparingPackage: "मास्टर कारीगर आपका अनूठा पैकेज तैयार कर रहे हैं। प्रत्येक वस्तु को जैविक गेहूं की भूसी और टिकाऊ केले के पत्तों में सावधानी से लपेटा जाएगा।",
      profitInfo: "24 घंटे के भीतर मुनाफे का 100% सीधे बुनकर/कुम्हार की सहकारी समिति को भेज दिया जाता है।",
      returnBtn: "कारीघर पर लौटें",
      free: "निःशुल्क"
    },
    artisans: {
      liveRooms: "लाइव रूम",
      createRoom: "रूम बनाएं",
      joinRoom: "रूम में शामिल हों",
      tipOfDay: "आज का सुझाव",
      hearthTitle: "कारीघर सामुदायिक मंच",
      createRoomSub: "एक नया लाइव सत्र शुरू करें और एक रूम कोड बनाएं।",
      joinRoomSub: "सक्रिय रूम से जुड़ने के लिए 4 अंकों का कोड दर्ज करें।",
      activeLabel: "सक्रिय कारीगर",
      liveNow: "लाइव अभी",
      editTopic: "चर्चा का विषय संपादित करें",
      currentTopic: "वर्तमान चर्चा का विषय",
      save: "सहेजें",
      cancel: "रद्द करें",
      editTopicBtn: "विषय संपादित करें",
      speaking: "बोल रहे हैं...",
      youArtisan: "आप (कारीगर)",
      invite: "आमंत्रित करें",
      muted: "म्यूट",
      micActive: "माइक्रोफ़ोन सक्रिय",
      youAreSpeaking: "आप बोल रहे हैं",
      holdToSpeak: "बोलने के लिए दबाए रखें",
      raiseHand: "हाथ उठाएं",
      leave: "छोड़ें",
      createLiveRoom: "लाइव रूम बनाएं",
      createRoomDesc: "अपने रूम का नाम दें। प्रतिभागियों के लिए 4 अंकों का प्रवेश कोड स्वचालित रूप से उत्पन्न होगा।",
      roomName: "Room Name",
      joinLiveRoom: "लाइव रूम में शामिल हों",
      joinRoomDesc: "सक्रिय वॉइस स्ट्रीम में शामिल होने के लिए रूम होस्ट द्वारा दिया गया 4 अंकों का कोड दर्ज करें।"
    },
    seller: {
      overview: "मुख्य सारांश",
      bazaar: "बाज़ार (स्टॉक)",
      orders: "आर्डर",
      earnings: "कमाई",
      sikho: "सीखो (पाठ)",
      sisters: "सहेलियां (समुदाय)",
      welcome: "स्वागत है, ",
      motto: "\"जब हम मिलकर आगे बढ़ते हैं, तो हमारा गाँव समृद्ध होता है।\"",
      pending: "लंबित",
      shipped: "भेज दिया",
      completed: "पूरा हुआ",
      ordersTitle: "ग्राहकों के आर्डर",
      ordersSub: "इंडिया पोस्ट कूरियर के जरिए सीधे खरीदारों के आर्डर भेजें",
      listenRequest: "ग्राहक की आवाज़ सुनें",
      shipPackageBtn: "कोरियर भेजें",
      markDeliveredBtn: "मिल गया",
      paidDelivered: "भुगतान और डिलीवर हुआ",
      availablePayout: "निकासी के लिए उपलब्ध",
      linkedBank: "जुड़ा हुआ बैंक खाता",
      lifetimeOverview: "कुल बिक्री सारांश",
      withdrawHistory: "बैंक निकासी और लेनदेन का इतिहास",
      withdrawBtn: "बैंक में भेजें",
      sikhoTitle: "सीखो (सीखें और आगे बढ़ें)",
      sikhoSub: "फ़ोटो, पैकेजिंग और सही मूल्य निर्धारण को बेहतर बनाने के लिए आपकी अपनी भाषा में पाठ",
      bazaarTitle: "बाज़ार (आपका स्टॉक)",
      bazaarSub: "वैश्विक स्टोर में उत्पाद जोड़ें और स्टॉक स्तर प्रबंधित करें",
      addCraftBtn: "नई रचना जोड़ें",
      stockQuantity: "स्टॉक संख्या",
      availableUnits: "इकाई उपलब्ध",
      outOfStock: "स्टॉक समाप्त",
      bankName: "बैंक का नाम",
      holderName: "खाताधारक",
      accNumber: "खाता संख्या",
      ifscCode: "IFSC कोड",
      payoutVerify: "निकासी सत्यापन",
      connectingSbi: "Connecting SBI Gateway...",
      transSuccessful: "ट्रांसफर सफल रहा!",
      sbiRef: "SBI संदर्भ संख्या",
      doneBtn: "पूरा हुआ",
      confirmTrans: "ट्रांसफर पक्का करें",
      recordingDesc: "रिकॉर्डिंग हो रही है...",
      voiceDescBtn: "बोलकर लिखें",
      listNewCraft: "नई शिल्प वस्तु जोड़ें",
      instantShow: "आपकी रचना तुरंत ग्राहकों को दिखाई देगी",
      craftName: "शिल्प का नाम",
      categoryLabel: "श्रेणी",
      priceLabel: "कीमत (₹)",
      stockLabel: "स्टॉक मात्रा",
      descriptionLabel: "विवरण",
      selectPicLabel: "शिल्प की तस्वीर चुनें",
      cancelBtn: "रद्द करें",
      addCraftSubmit: "शिल्प जोड़ें",
      lessonsHeader: "सीखो (सीखें और आगे बढ़ें)",
      lessonsSubText: "फ़ोटो, पैकेजिंग और सही मूल्य निर्धारण को बेहतर बनाने के लिए आपकी अपनी भाषा में पाठ",
      lessonPhotography: "पाठ 1 • फोटोग्राफी",
      lessonLogistics: "पाठ 2 • पैकेजिंग",
      lessonCourier: "पाठ 3 • डाकघर कूरियर",
      lessonBusiness: "पाठ 4 • व्यापार की बातें",
      lowInternet: "धीमा इंटरनेट मोड",
      lowInternetSub: "डेटा बचाने के लिए केवल ऑडियो चल रहा है। हिंदी वर्णन सक्रिय है।",
      markDone: "पाठ पूरा करें"
    },
    sellerOnboarding: {
      welcomeTitle: "KariGhar में आपका स्वागत है",
      welcomeSubtitle: "\"अपनी कला बेचो, सीधा घर से।\"",
      newHere: "मैं यहाँ नया हूँ",
      haveAccount: "मेरा एक खाता है →",
      voiceWelcome: "\"स्वागत है। अपने शिल्प को बेचना शुरू करने के लिए 'मैं यहाँ नया हूँ' पर टैप करें।\"",
      browseCustomer: "ग्राहक के रूप में ब्राउज़ करें",
      consumerStore: "ग्राहक स्टोर",
      namasteSister: "\"नमस्ते बहन, आइए आपकी यात्रा शुरू करें।\"",
      tellName: "हमें अपना नाम बताएं",
      fullName: "पूरा नाम",
      placeholderName: "जैसे: राधा देवी",
      speakOrType: "माइक्रोफ़ोन में साफ़ बोलें या कीबोर्ड का उपयोग करके अपना नाम टाइप करें।",
      next: "आगे बढ़ें →",
      needHelpWatch: "सहायता चाहिए? देखें: KariGhar का उपयोग कैसे करें",
      voiceGuidanceStep1: "आइए आपकी प्रोफ़ाइल बनाएं। कृपया अपना पूरा नाम बताएं।",
      createSecretCode: "अपना गुप्त कोड बनाएं",
      rememberCode: "\"ऐसा कोड रखें जो आपको हमेशा याद रहे\"",
      secretCodeLabel: "गुप्त कोड (पासवर्ड)",
      placeholderCode: "जैसे: 1234",
      aageBadhein: "आगे बढ़ें →",
      listening: "मैं सुन रही हूँ...",
      watchTypeCode: "देखें: अपना कोड कैसे टाइप करें",
      empoweringArtisansDesc: "शिल्प और कोड: कारीगरों का सशक्तिकरण — हेरिटेज हर्थ ऐप का उपयोग करना सीखें!",
      voiceGuidanceStep2: "एक साधारण कोड चुनें जो आपको याद रहे। मैं इसे सुरक्षित रखूंगी।",
      whereAreYouFrom: "आप कहाँ से हैं?",
      enterPhoneLocation: "\"अपना फ़ोन नंबर और स्थान बताएं\"",
      voiceGuidanceStep3: "\"अपना फ़ोन नंबर और शहर चुनें ताकि ग्राहक आपको ढूंढ सकें।\"",
      phoneNumberLabel: "फ़ोन नंबर",
      stateLabel: "राज्य",
      districtLabel: "जिला",
      selectState: "— राज्य चुनें —",
      selectDistrict: "— जिला चुनें —",
      empoweringArtisansTitle: "शिल्प और कोड: कारीगरों का सशक्तिकरण",
      welcomeBackSister: "\"वापसी पर स्वागत है, बहन। आपका शिल्प हम सभी को प्रेरित करता है।\"",
      enterNamePass: "कृपया अपना नाम और पासवर्ड दर्ज करें।",
      loginLabel: "लॉगिन →"
    },
    chatbot: {
      tooltipText: "कोई समस्या आ रही है?",
      tooltipSub: "टैप करें, मैं यहाँ आपका मार्गदर्शन करने के लिए हूँ! ❀",
      onlineSupport: "ऑनलाइन और निर्देशित सहायता",
      assistantName: "KariGhar सहायक",
      inputPlaceholder: "प्रश्न पूछें...",
      footerBranding: "भारतीय शिल्प का संरक्षण • KariGhar साथी",
      introDefault: "नमस्ते! मैं आपकी KariGhar डिजिटल साथी हूँ। आज हमारे कारीगर मार्केटप्लेस में आपका मार्गदर्शन कैसे कर सकती हूँ? ❀",
      introHome: "KariGhar में आपका स्वागत है! मैं हमारी कारीगर कहानियों में आपका मार्गदर्शन कर सकती हूँ, हस्तशिल्प श्रेणियों को ब्राउज़ करने में मदद कर सकती हूँ, या हमारे प्रत्यक्ष निष्पक्ष-व्यापार मॉडल को समझा सकती हूँ। मैं आपकी क्या मदद कर सकती हूँ? ❀",
      introCategories: "हमारा संग्रह ब्राउज़ कर रहे हैं? आप विशिष्ट भारतीय जिलों के आधार पर शिल्प फ़िल्टर कर सकते हैं या अपने बजट से मेल खाने के लिए मूल्य स्लाइडर का उपयोग कर सकते हैं। कुछ अनूठा ढूंढने में सहायता चाहिए? ❀",
      introProduct: "यह विरासत रचना क्षेत्रीय जैविक सामग्रियों से हस्तनिर्मित है! क्या आप 3-चरणीय कारीगरी प्रक्रिया की समीक्षा करना चाहेंगे या शिपिंग सुरक्षा की जांच करना चाहेंगे? ❀",
      introSeller: "नमस्ते भागीदार! अपने कारीगर कार्यक्षेत्र में, आप हमारे निष्पक्ष-व्यापार मूल्य निर्धारण उपकरण का उपयोग करके क्षेत्रीय जीवन यापन वेतन की गणना कर सकते हैं, सीधे व्हाट्सएप चैट लिंक उत्पन्न कर सकते हैं, या एक ऑडियो विवरण रिकॉर्ड कर सकते हैं। सहायता चाहिए? ❀",
      introHelp: "आप सहायता केंद्र पर पहुँच गए हैं! मैं हिंदी और अंग्रेजी में सक्षम हूँ। नीचे कोई भी प्रश्न टाइप करें या त्वरित उत्तर के लिए किसी चिप पर क्लिक करें! ❀",
      introLogin: "हमारे नमस्ते प्रमाणीकरण पैनल में आपका स्वागत है! आप आसानी से एक ग्राहक या विक्रेता के रूप में पंजीकरण कर सकते हैं, अपनी प्रोफ़ाइल तस्वीर अपलोड कर सकते हैं, और सत्यापित करने के लिए मॉक ओटीपी कोड '1234' दर्ज कर सकते हैं। ❀",
      ackHindi: "नमस्ते! अब मैं हिन्दी में आपकी सहायता के लिए तैयार हूँ। आप अपना प्रश्न पूछ सकते हैं। ❀",
      ackEnglish: "बहुत बढ़िया! अब मैं अंग्रेजी (भारत) में आपकी सहायता के लिए तैयार हूँ। आज मैं आपकी क्या मदद कर सकती हूँ? ❀",
      ackKannada: "ನಮಸ್ತೆ! ಈಗ ನಾನು ಕನ್ನಡದಲ್ಲಿ ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧನಾಗಿದ್ದೇನೆ. ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಬಹುದು. ❀",
      errorMsg: "नमस्ते! मुझे अभी कनेक्ट करने में समस्या हो रही है। कृपया थोड़ी देर में पुनः प्रयास करें, या अक्सर पूछे जाने वाले प्रश्नों के लिए हमारे सहायता पृष्ठ पर जाएँ। 🙏",
      chips: {
        livingWage: "लिविंग वेज कैलकुलेटर",
        whatsapp: "व्हाट्सएप चैट सेटअप",
        voiceRec: "वॉयस रिकॉर्डर सहायता",
        howOrder: "ऑर्डर कैसे करें?",
        directFair: "प्रत्यक्ष निष्पक्ष-व्यापार?",
        meetArtisans: "हमारे कारीगरों से मिलें",
        fragileShip: "नाजुक शिपिंग",
        loomWeave: "करघा बुनाई प्रक्रिया",
        reviewGuide: "समीक्षा दिशानिर्देश",
        genGuide: "सामान्य वेबसाइट गाइड",
        otpVerify: "ओटीपी सत्यापन",
        packagingStd: "पैकेजिंग मानक"
      }
    }
  },
  kn: {
    nav: {
      story: "ನಮ್ಮ ಕಥೆ",
      collections: "ಕಲಾ ಸಂಗ್ರಹಗಳು",
      artisans: "ಮಹಿಳಾ ಕುಶಲಕರ್ಮಿಗಳು",
      searchPlaceholder: "ಕುಶಲಕಲೆಗಳನ್ನು ಹುಡುಕಿ...",
      languageSelect: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
      cart: "ಖರೀದಿ ಚೀಲ",
      signOut: "ಲಾಗ್ ಔಟ್",
      loginRegister: "ಲಾಗಿನ್ / ನೋಂದಣಿ",
      store: "ಮಳಿಗೆ"
    },
    home: {
      heroTitle: "ಡಿಜಿಟಲ್ ವ್ಯಾಪಾರದ ಮೂಲಕ ಭಾರತೀಯ ಕುಶಲಕರ್ಮಿಗಳ ಸಬಲೀಕರಣ",
      heroSubtitle: "ಯಾವುದೇ ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲದೆ ನೇರವಾಗಿ ನಿಮ್ಮ ಮನೆಬಾಗಿಲಿಗೆ ತಲುಪುವ ಕೈಯಿಂದ ತಯಾರಿಸಿದ ಕರಕುಶಲ ವಸ್ತುಗಳು.",
      exploreBtn: "ಮಾರುಕಟ್ಟೆ ಅನ್ವೇಷಿಸಿ",
      becomeSellerBtn: "ಮಾರಾಟಗಾರರಾಗಿ",
      badgeText: "ಕರಕುಶಲ ಸಂರಕ್ಷಣೆ • ಕೈಗಳಿಗೆ ಗೌರವ",
      womenStat: "ಮಹಿಳೆಯರ ಸಬಲೀಕರಣ",
      districtsStat: "ಕುಶಲಕಲೆ ಪ್ರದೇಶಗಳು",
      productsStat: "ಕೈಯಿಂದ ತಯಾರಿಸಿದ ವಸ್ತುಗಳು",
      paletteTitle: "ಕುಶಲಕರ್ಮಿಗಳ ಕಲಾಕೃತಿಗಳು",
      paletteSub: "ಸಾಂಪ್ರದಾಯಿಕ ವರ್ಗಗಳು",
      handloomTitle: "ಕೈಮಗ್ಗ",
      handloomSub: "ಪರಂಪರೆಯ ಎಳೆಗಳು",
      potteryTitle: "ಮಡಕೆಗಾರಿಕೆ",
      potterySub: "ಪ್ರೀತಿಯಿಂದ ರೂಪಿಸಿದ ಮಣ್ಣು",
      jewelryTitle: "ಆಭರಣಗಳು",
      jewelrySub: "ಇತಿಹಾಸದ ಆಭರಣಗಳು",
      paintingsTitle: "ಚಿತ್ರಕಲೆಗಳು",
      paintingsSub: "ನಂಬಿಕೆಯ ಬಣ್ಣಗಳು",
      embroideryTitle: "ಕಸೂತಿ",
      embroiderySub: "ಕಥೆ ಹೇಳುವ ಹೊಲಿಗೆಗಳು",
      curationSub: "ಆಯ್ದ ಅತ್ಯುತ್ತಮ ಕಲಾಕೃತಿಗಳು",
      curationTitle: "ಈ ತಿಂಗಳ ಆಯ್ದ ಕಲಾಕೃತಿಗಳು",
      viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
      signature: "ವಿಶೇಷ ಸಹಿ",
      artisanLabel: "ಕುಶಲಕರ್ಮಿ:",
      spotlightBadge: "ಕರಕುಶಲ ಧ್ವನಿಗಳು",
      meetParvati: "ಪಾರ್ವತಿ ದೇವಿಯವರನ್ನು ಭೇಟಿ ಮಾಡಿ",
      parvatiDesc: "ಮಧ್ಯಪ್ರದೇಶದ ಹೃದಯಭಾಗದ ಪ್ರಸಿದ್ಧ ನೇಯ್ಗೆಗಾರ್ತಿಯಾದ ಪಾರ್ವತಿಯವರು ಕಳೆದ 40 ವರ್ಷಗಳಿಂದ ತಮ್ಮ ಕೈಮಗ್ಗ ಕಲೆಯನ್ನು ಕರಗತ ಮಾಡಿಕೊಂಡಿದ್ದಾರೆ. ಅವರ ಕರಕುಶಲ ವಸ್ತುಗಳು ಕಾರೀಘರ್ ಮೂಲಕ ಜಾಗತಿಕ ಸಂಗ್ರಾಹಕರನ್ನು ತಲುಪುತ್ತಿದ್ದು, ಸಾಂಪ್ರದಾಯಿಕ ವಿಧಾನಗಳ ಸಂರಕ್ಷಣೆ ಮತ್ತು ಅವರ ಹೆಣ್ಣುಮಕ್ಕಳು ಈ ಪರಂಪರೆಯನ್ನು ಕಲಿಯಲು ನೆರವಾಗಿದೆ.",
      parvatiQuote: "\"ಪ್ರತಿಯೊಂದು ಎಳೆಯೂ ನನ್ನ ಪೂರ್ವಜರ ಕಥೆಯನ್ನು ಹೇಳುತ್ತದೆ. ಡಿಜಿಟಲ್ ವ್ಯಾಪಾರವು ನಮ್ಮ ಕುಟುಂಬಕ್ಕೆ ಉತ್ತಮ ಭವಿಷ್ಯವನ್ನು ನೀಡುತ್ತದೆ.\"",
      districtLabel: "ಜಿಲ್ಲೆ",
      districtVal: "ಮಹೇಶ್ವರ",
      specLabel: "ವಿಶೇಷತೆ",
      specVal: "ಅಜ್ರಖ್ ನೇಯ್ಗೆ",
      readStoryBtn: "ಅವರ ಕಥೆಯನ್ನು ಓದಿ",
      modalTitle: "ಪಾರ್ವತಿ ದೇವಿಯವರ ಕಥೆ",
      modalSub: "ಪಾರಂಪರಿಕ ನೇಕಾರರು, ಮಹೇಶ್ವರ",
      modalPara1: "ಪಾರ್ವತಿ ದೇವಿಯವರು ಪ್ರಶಸ್ತಿ ವಿಜೇತ ಕುಶಲಕರ್ಮಿಯಾಗಿದ್ದು, ಮಹೇಶ್ವರದಲ್ಲಿರುವ ತಮ್ಮ ಹಳೆಯ ಮನೆಯಲ್ಲಿ ವಾಸಿಸುತ್ತಿದ್ದಾರೆ. ಇವರು ಚಿನ್ನದ ಜರಿ ಎಳೆಗಳು ಮತ್ತು ನೈಸರ್ಗಿಕ ಬಣ್ಣಗಳನ್ನು ಬಳಸಿ ಕೈಮಗ್ಗದ ರೇಷ್ಮೆ ಸೀರೆಗಳನ್ನು ತಯಾರಿಸುವುದರಲ್ಲಿ ಪರಿಣತಿ ಹೊಂದಿದ್ದಾರೆ.",
      modalPara2: "\"ಕಾರೀಘರ್ ಆರಂಭವಾಗುವ ಮೊದಲು, ಸ್ಥಳೀಯ ವ್ಯಾಪಾರಿಗಳು ನಮ್ಮ ರೇಷ್ಮೆ ಕರಕುಶಲ ವಸ್ತುಗಳನ್ನು ಅತ್ಯಂತ ಕಡಿಮೆ ಬೆಲೆಗೆ ಖರೀದಿಸುತ್ತಿದ್ದರು ಮತ್ತು ಹಣ ನೀಡಲು ತಿಂಗಳುಗಟ್ಟಲೆ ವಿಳಂಬ ಮಾಡುತ್ತಿದ್ದರು. ಇಂದು, ನಮ್ಮ ರೇಷ್ಮೆ ವಸ್ತುಗಳು ಲಂಡನ್, ನ್ಯೂಯಾರ್ಕ್ ಮತ್ತು ಟೋಕಿಯೊದ ಕಲಾ ಸಂಗ್ರಾಹಕರನ್ನು ಯೋಗ್ಯ ಮತ್ತು ಸುಸ್ಥಿರ ಬೆಲೆಯಲ್ಲಿ ತಲುಪುತ್ತಿವೆ. ಹಣವು 24 ಗಂಟೆಗಳ ಒಳಗೆ ನೇರವಾಗಿ ನಮ್ಮ ಸಹಕಾರಿ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತದೆ.\"",
      modalPara3: "ಪ್ರಸ್ತುತ, ಪಾರ್ವತಿಯವರು 12 ಸ್ಥಳೀಯ ಹುಡುಗಿಯರಿಗೆ ಕಾರ್ಯಾಗಾರವನ್ನು ನಡೆಸುತ್ತಿದ್ದು, ತಮ್ಮ 300 ವರ್ಷಗಳಷ್ಟು ಹಳೆಯದಾದ ನೇಯ್ಗೆ ವಿನ್ಯಾಸಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳುವ ಮೂಲಕ ಈ ಸುಂದರ ಪರಂಪರೆಯು ಡಿಜಿಟಲ್ ಯುಗದಲ್ಲೂ ಉಳಿಯುವಂತೆ ಮಾಡುತ್ತಿದ್ದಾರೆ."
    },
    categories: {
      badge: "ಸಂಗ್ರಾಹಕರ ಕ್ಯಾಟಲಾಗ್",
      title: "ಕುಶಲಕಲೆಯ ಆಯ್ದ ಕಲಾಕೃತಿಗಳು",
      filters: "ಫಿಲ್ಟರ್‌ಗಳು",
      clearAll: "ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ",
      craftType: "ಕುಶಲಕಲೆಯ ಪ್ರಕಾರ",
      priceRange: "ಬೆಲೆ ಶ್ರೇಣಿ",
      upTo: "ವರೆಗೆ",
      minRating: "ಕನಿಷ್ಠ ರೇಟಿಂಗ್",
      andUp: " ಮತ್ತು ಮೇಲ್ಪಟ್ಟು",
      allRatings: "ಎಲ್ಲಾ ರೇಟಿಂಗ್‌ಗಳು",
      districtOrigin: "ಮೂಲ ಜಿಲ್ಲೆ",
      allDistricts: "ಎಲ್ಲಾ ಜಿಲ್ಲೆಗಳು",
      showing: "ತೋರಿಸಲಾಗುತ್ತಿದೆ",
      results: "ಫಲಿತಾಂಶಗಳು",
      for: "ಗೆ",
      sortBy: "ವರ್ಗೀಕರಿಸಿ:",
      mostRecent: "ಇತ್ತೀಚಿನದು",
      priceLowHigh: "ಬೆಲೆ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚಿಗೆ",
      priceHighLow: "ಬೆಲೆ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆಗೆ",
      topRated: "ಹೆಚ್ಚು ರೇಟಿಂಗ್ ಪಡೆದದ್ದು",
      noMatches: "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಸಿಗಲಿಲ್ಲ",
      noMatchesSub: "ಇತರ ಕರಕುಶಲ ವಸ್ತುಗಳನ್ನು ಹುಡುಕಲು ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳು, ಬೆಲೆ ಮಿತಿಗಳು ಅಥವಾ ಹುಡುಕಾಟ ಪದಗಳನ್ನು ಬದಲಾಯಿಸಿ ನೋಡಿ.",
      resetFilters: "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ",
      signature: "ವಿಶೇಷ ಸಹಿ",
      openAssistant: "ಕಾರೀಘರ್ ಸಹಾಯಕರನ್ನು ತೆರೆಯಿರಿ"
    },
    product: {
      notFound: "ವಸ್ತು ಪತ್ತೆಯಾಗಿಲ್ಲ",
      notFoundSub: "ನೀವು ಹುಡುಕುತ್ತಿರುವ ಕೈಯಿಂದ ತಯಾರಿಸಿದ ಕರಕುಶಲ ವಸ್ತು ನಮ್ಮ ಕ್ಯಾಟಲಾಗ್‌ನಲ್ಲಿ ಇಲ್ಲ.",
      backCollections: "ಸಂಗ್ರಹಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
      addedToCart: "ಖರೀದಿ ಚೀಲಕ್ಕೆ ಸೇರಿಸಲಾಗಿದೆ!",
      removedWishlist: "ನಿಮ್ಮ ಸಂಗ್ರಾಹಕರ ಆಸೆಗಳ ಪಟ್ಟಿಯಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ.",
      addedWishlist: "ನಿಮ್ಮ ಸಂಗ್ರಾಹಕರ ಆಸೆಗಳ ಪಟ್ಟಿಗೆ ಸೇರಿಸಲಾಗಿದೆ!",
      verifiedReview: "ಧನ್ಯವಾದಗಳು! ನಿಮ್ಮ ಪರಿಶೀಲಿಸಿದ ಸಂಗ್ರಾಹಕರ ವಿಮರ್ಶೆಯನ್ನು ಸೇರಿಸಲಾಗಿದೆ.",
      home: "ಹೋಮ್",
      collections: "ಸಂಗ್ರಹಗಳು",
      rating: "ರೇಟಿಂಗ್",
      collectorReviews: "ಸಂಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು",
      handMadeBhuj: "ಕೈಯಿಂದ ತಯಾರಿಸಿದ • ಕಚ್",
      ecoFriendly: "ಪರಿಸರ ಸ್ನೇಹಿ",
      sustainable: "ಸುಸ್ಥಿರ",
      stockStatus: "ದಾಸ್ತಾನು ಸ್ಥಿತಿ",
      addToCart: "ಖರೀದಿ ಚೀಲಕ್ಕೆ ಸೇರಿಸಿ",
      sameCollection: "ಇದೇ ಸಂಗ್ರಹದಿಂದ",
      whatCollectorsSay: "ನಮ್ಮ ಸಂಗ್ರಾಹಕರು ಏನು ಹೇಳುತ್ತಾರೆ",
      basedOn: "ರ ಆಧಾರದ ಮೇಲೆ",
      writeReview: "ವಿಮರ್ಶೆ ಬರೆಯಿರಿ",
      star5: "5 ನಕ್ಷತ್ರ",
      star4: "4 ನಕ್ಷತ್ರ",
      star3: "3 ನಕ್ಷತ್ರ",
      noReviewsYet: "ಇನ್ನೂ ಯಾವುದೇ ಸಂಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳಿಲ್ಲ. ಈ ಕಲಾಕೃತಿಯ ಕುರಿತು ನಿಮ್ಮ ಅಭಿಪ್ರಾಯಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳುವ ಮೊದಲ ವ್ಯಕ್ತಿಯಾಗಿ!",
      selectRating: "ರೇಟಿಂಗ್ ಆಯ್ಕೆಮಾಡಿ:",
      yourName: "ನಿಮ್ಮ ಹೆಸರು",
      collectorReviewText: "ಸಂಗ್ರಾಹಕರ ವಿಮರ್ಶ",
      reviewPlaceholder: "ಕರಕುಶಲ ವಸ್ತುವಿನ ವಿನ್ಯಾಸ, ತೂಕ, ವಿವರಣೆ ಮತ್ತು ಪ್ಯಾಕೇಜಿಂಗ್ ಅನ್ನು ವಿವರಿಸಿ...",
      submitReview: "ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಿ",
      storyOf: "ರ ಕಥೆ",
      bhujKutch: "ಭುಜ್, ಕಚ್ ಜಿಲ್ಲೆ",
      closeModal: "ವಿವರಣೆ ಮುಚ್ಚಿ"
    },
    help: {
      badge: "ಕುಶಲಕರ್ಮಿಗಳ ನೆರವು ಕೇಂದ್ರ",
      title: "ನಿಮ್ಮ ಸೃಜನಶೀಲತೆಗೆ ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
      uploadTitle: "ಉತ್ಪನ್ನ ಅಪ್‌ಲೋಡ್",
      uploadDesc: "ಹೆಚ್ಚಿನ ರೆಸಲ್ಯೂಶನ್ ಚಿತ್ರಗಳು ಮತ್ತು ನಿಮ್ಮ ಸಾಂಪ್ರದಾಯಿಕ ಕಥೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಕಲೆಯನ್ನು ಹೇಗೆ ಪ್ರದರ್ಶಿಸಬೇಕೆಂದು ತಿಳಿಯಿರಿ.",
      pricingTitle: "ಬೆಲೆ ನಿಗದಿ ನೆರವು",
      pricingDesc: "ನ್ಯಾಯಯುತ ವ್ಯಾಪಾರದ ಬೆಲೆ ನಿಗದಿ, ಕಚ್ಚಾ ವಸ್ತುಗಳ ವೆಚ್ಚದ ಲೆಕ್ಕಾಚಾರ ಮತ್ತು ಜಾಗತಿಕ ಮಾರುಕಟ್ಟೆ ಸ್ಥಾನೀಕರಣದ ಕುರಿತು ಮಾರ್ಗದರ್ಶನ.",
      shippingTitle: "ರವಾನೆ ಮತ್ತು ಲಾಜಿಸ್ಟಿಕ್ಸ್",
      shippingDesc: "ಪರಿಸರ ಸ್ನೇಹಿ ಪ್ಯಾಕೇಜಿಂಗ್ ನಿಯಮಗಳು ಮತ್ತು ಸೂಕ್ಷ್ಮ ಕರಕುಶಲ ವಸ್ತುಗಳ ನಿರ್ವಹಣೆಯಲ್ಲಿ ಅನುಭವವಿರುವ ಜಾಗತಿಕ ರವಾನೆ ಪಾಲುದಾರರು.",
      pledgeTitle: "ಕುಶಲಕರ್ಮಿಗಳ ಭರವಸೆ",
      pledgeDesc: "100% ಪಾರದರ್ಶಕತೆ, ಸಾಂಪ್ರದಾಯಿಕ ಪರಂಪರೆಯ ಸಂರಕ್ಷಣೆ ಮತ್ತು ತಕ್ಷಣದ ಸಹಕಾರಿ ಬ್ಯಾಂಕ್ ಪಾವತಿಗೆ ನಮ್ಮ ಬದ್ಧತೆ.",
      communityStory: "ಸಮುದಾಯದ ಕಥೆ",
      storyTitle: "ಡಿಜಿಟಲ್ ಉಪಸ್ಥಿತಿಯ ಮೂಲಕ ತಲೆಮಾರುಗಳನ್ನು ಬೆಸೆಯುವುದು",
      storyDesc: "ದೂರದ ಕಚ್ ಹಳ್ಳಿಯೊಂದರಲ್ಲಿ ರಾವ್ ಅವರ ಕೌಟುಂಬಿಕ ಮಡಕೆ ತಯಾರಿಕೆಯ ಕಾರ್ಯಾಗಾರವು ಕ್ಯೋಟೋ ಮತ್ತು ಸ್ಯಾನ್ ಫ್ರಾನ್ಸಿಸ್ಕೋದ ಕಲಾ ಸಂಗ್ರಾಹಕರನ್ನು ತಲುಪಿ, ಆದಾಯವನ್ನು ಹೇಗೆ ದ್ವಿಗುಣಗೊಳಿಸಿತು ಮತ್ತು ಮಕ್ಕಳು ತಮ್ಮ ಐದು ತಲೆಮಾರಿನ ಪರಂಪರೆಯನ್ನು ಮುಂದುವರಿಸಲು ಹೇಗೆ ನೆರವಾಯಿತು."
    },
    login: {
      title: "ನಮಸ್ತೆ, ಸಂಗ್ರಾಹಕರೇ",
      sub: "ನಿಮ್ಮ ಕಾರೀಘರ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಮತ್ತು ಸಂಗ್ರಾಹಕರ ಆಸೆಗಳ ಪಟ್ಟಿಯನ್ನು ವೀಕ್ಷಿಸಲು ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ ಅಥವಾ ನೋಂದಾಯಿಸಿ.",
      signInRegister: "ಲಾಗಿನ್ / ನೋಂದಣಿ",
      createAccount: "ಖಾತೆ ರಚಿಸಿ",
      welcomeBack: "ಸ್ವಾಗತ",
      joinMarketplace: "ಖರೀದಿಸಲು ಅಥವಾ ಮಾರಾಟ ಮಾಡಲು ನಮ್ಮ ಮಾರುಕಟ್ಟೆಗೆ ಸೇರಿಕೊಳ್ಳಿ.",
      welcomeBackSub: "ಕಾರೀಘರ್‌ಗೆ ಸುಸ್ವಾಗತ.",
      customer: "ಗ್ರಾಹಕರು",
      sellerArtisan: "ಮಾರಾಟಗಾರ ಕುಶಲಕರ್ಮಿ",
      changeProfile: "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ ಬದಲಾಯಿಸಿ",
      uploadProfile: "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
      fullName: "ಪೂರ್ಣ ಹೆಸರು",
      enterName: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
      emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
      password: "ಪಾಸ್ವರ್ಡ್",
      phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
      creatingAccount: "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
      signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...",
      logIn: "ಲಾಗಿನ್ ಮಾಡಿ",
      orConnect: "ಅಥವಾ ಇದರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ",
      continueGoogle: "ಗೂಗಲ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
      alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?",
      dontHaveAccount: "ಖಾತೆ ಹೊಂದಿಲ್ಲವೇ?",
      signUp: "ಸೈನ್ ಅಪ್ ಮಾಡಿ"
    },
    profile: {
      partner: "ಪಾಲುದಾರರು",
      collectorId: "ಸಂಗ್ರಾಹಕರ ಐಡಿ",
      accountSettings: "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್ಸ್",
      editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
      saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
      cancel: "ರದ್ದುಮಾಡಿ",
      welcomeProfile: "ನಿಮ್ಮ ಕಾರೀಘರ್ ಸಂಗ್ರಾಹಕರ ಪ್ರೊಫೈಲ್‌ಗೆ ಸುಸ್ವಾಗತ. ಇಲ್ಲಿ ನಿಮ್ಮ ಪರಿಶೀಲಿಸಿದ ಗುರುತಿನ ವಿವರಗಳನ್ನು ನೀವು ನಿರ್ವಹಿಸಬಹುದು.",
      statusLabel: "ಸ್ಥಿತಿ:",
      activeVerification: "ಸಕ್ರಿಯ ಸಂಗ್ರಾಹಕರ ಪರಿಶೀಲನೆ",
      wishlistTitle: "ಸಂಗ್ರಾಹಕರ ಆಸೆಗಳ ಪಟ್ಟಿ"
    },
    cart: {
      orderComplete: "ಆರ್ಡರ್ ಪೂರ್ಣಗೊಂಡಿದೆ",
      yourCart: "ನಿಮ್ಮ ಕಾರೀಘರ್ ಕಾರ್ಟ್",
      cartEmpty: "ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ.",
      cartEmptySub: "ಕಚ್, ಕಾಶ್ಮೀರ ಮತ್ತು ವಾರಣಾಸಿಯ ನೈಜ ಮತ್ತು ಸುಂದರವಾದ ಕೈಯಿಂದ ತಯಾರಿಸಿದ ಕರಕುಶಲ ವಸ್ತುಗಳಿಂದ ನಿಮ್ಮ ಮನೆಯನ್ನು ಅಲಂಕರಿಸಿ.",
      startExploring: "ಅನ್ವೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ",
      subtotal: "ಕಾರ್ಟ್ ಒಟ್ಟು ಮೊತ್ತ",
      shipping: "ಪರಿಸರ ಪ್ಯಾಕೇಜಿಂಗ್ ಮತ್ತು ಶಿಪ್ಪಿಂಗ್",
      total: "ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಹಣ",
      pledgeText: "🌱 ಕಾರೀಘರ್ ಪ್ರತಿಜ್ಞೆ: 100% ಜೈವಿಕ ವಿಘಟನೀಯ ಗೋಧಿ ಹೊಟ್ಟು ಮತ್ತು ಮರದ ಚಕ್ಕೆಗಳಲ್ಲಿ ಪ್ಯಾಕ್ ಮಾಡಿ ರವಾನಿಸಲಾಗುತ್ತದೆ.",
      placeOrder: "ಆರ್ಡರ್ ಮಾಡಿ",
      securingTransaction: "ಕುಶಲಕರ್ಮಿಗಳ ವಹಿವಾಟು ಸುರಕ್ಷಿತಗೊಳಿಸಲಾಗುತ್ತಿದೆ",
      securingSub: "ನೇಕಾರರು ಮತ್ತು ಕುಂಬಾರರನ್ನು ಬೆಂಬಲಿಸಲು ನೇರವಾಗಿ ಗ್ರಾಮೀಣ ಬ್ಯಾಂಕಿಂಗ್ ನೆಟ್‌ವರ್ಕ್‌ಗಳೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಲಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ಮುಚ್ಚಬೇಡಿ.",
      orderPlacedSuccess: "ನಮಸ್ತೆ. ಆರ್ಡರ್ ಯಶಸ್ವಿಯಾಗಿದೆ!",
      receiptCreated: "ನಿಮ್ಮ ಸಂಗ್ರಾಹಕರ ರಶೀದಿಯನ್ನು ರಚಿಸಲಾಗಿದೆ.",
      preparingPackage: "ಪ್ರಸಿದ್ಧ ಕುಶಲಕರ್ಮಿಗಳು ನಿಮ್ಮ ಪ್ಯಾಕೇಜ್ ಸಿದ್ಧಪಡಿಸುತ್ತಿದ್ದಾರೆ. ಪ್ರತಿಯೊಂದು ವಸ್ತುವನ್ನು ಸಾವಯವ ಗೋಧಿ ಹೊಟ್ಟು ಮತ್ತು ಬಾಳೆ ಎಲೆಗಳಲ್ಲಿ ಎಚ್ಚರಿಕೆಯಿಂದ ಪ್ಯಾಕ್ ಮಾಡಲಾಗುತ್ತದೆ.",
      profitInfo: "ಗಳಿಸಿದ ಲಾಭದ 100% ಅನ್ನು 24 ಗಂಟೆಗಳ ಒಳಗೆ ನೇರವಾಗಿ ನೇಕಾರರು/ಕುಂಬಾರರ ಸಹಕಾರ ಸಂಘಕ್ಕೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.",
      returnBtn: "ಕಾರೀಘರ್‌ಗೆ ಹಿಂತಿರುಗಿ",
      free: "ಉಚಿತ"
    },
    artisans: {
      liveRooms: "ಲೈವ್ ರೂಮ್‌ಗಳು",
      createRoom: "ರೂಮ್ ರಚಿಸಿ",
      joinRoom: "ರೂಮ್‌ಗೆ ಸೇರಿಕೊಳ್ಳಿ",
      tipOfDay: "ಇಂದಿನ ಸಲಹೆ",
      hearthTitle: "ಕಾರೀಘರ್ ಸಮುದಾಯದ ವೇದಿಕೆ",
      createRoomSub: "ಹೊಸ ಲೈವ್ ಸಂವಾದವನ್ನು ಪ್ರಾರಂಭಿಸಿ ಮತ್ತು ಪ್ರವೇಶ ಕೋಡ್ ರಚಿಸಿ.",
      joinRoomSub: "ಸಕ್ರಿಯ ರೂಮ್‌ಗೆ ಸಂಪರ್ಕಿಸಲು 4-ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ.",
      activeLabel: "ಸಕ್ರಿಯ ಕುಶಲಕರ್ಮಿಗಳು",
      liveNow: "ಲೈವ್ ಈಗ",
      editTopic: "ಸಂವಾದದ ವಿಷಯವನ್ನು ಸಂಪಾದಿಸಿ",
      currentTopic: "ಪ್ರಸ್ತುತ ಸಂವಾದದ ವಿಷಯ",
      save: "ಉಳಿಸಿ",
      cancel: "ರದ್ದುಮಾಡಿ",
      editTopicBtn: "ವಿಷಯ ಸಂಪಾದಿಸಿ",
      speaking: "ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ...",
      youArtisan: "ನೀವು (ಕುಶಲಕರ್ಮಿ)",
      invite: "ಆಹ್ವಾನಿಸಿ",
      muted: "ಮ್ಯೂಟ್ ಮಾಡಲಾಗಿದೆ",
      micActive: "ಮೈಕ್ರೊಫೋನ್ ಸಕ್ರಿಯವಾಗಿದೆ",
      youAreSpeaking: "ನೀವು ಮಾತನಾಡುತ್ತಿದ್ದೀರಿ",
      holdToSpeak: "ಮಾತನಾಡಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ",
      raiseHand: "ಕೈ ಎತ್ತಿ",
      leave: "ನಿರ್ಗಮಿಸಿ",
      createLiveRoom: "ಲೈವ್ ರೂಮ್ ರಚಿಸಿ",
      createRoomDesc: "ನಿಮ್ಮ ರೂಮ್‌ಗೆ ಹೆಸರಿಡಿ. ಭಾಗವಹಿಸುವವರಿಗಾಗಿ 4-ಅಂಕಿಯ ಪ್ರವೇಶ ಕೋಡ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ರಚನೆಯಾಗುತ್ತದೆ.",
      roomName: "Room Name",
      joinLiveRoom: "ಲೈವ್ ರೂಮ್‌ಗೆ ಸೇರಿಕೊಳ್ಳಿ",
      joinRoomDesc: "ಸಕ್ರಿಯ ವಾಯ್ಸ್ ಸ್ಟ್ರೀಮ್‌ಗೆ ಸೇರಲು ರೂಮ್ ಹೋಸ್ಟ್ ನೀಡಿದ 4-ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ."
    },
    seller: {
      overview: "ಅವಲೋಕನ",
      bazaar: "ಬಜಾರ್ (ದಾಸ್ತಾನು)",
      orders: "ಆರ್ಡರ್‌ಗಳು",
      earnings: "ಗಳಿಕೆ",
      sikho: "ಕಲಿಯಿರಿ (ಸಿಖೋ)",
      sisters: "ಸಹೋದರಿಯರ ಬಳಗ",
      welcome: "ಸ್ವಾಗತ, ",
      motto: "\"ನಾವು ಒಟ್ಟಿಗೆ ಬೆಳೆದಾಗ, ನಮ್ಮ ಗ್ರಾಮವು ಅಭಿವೃದ್ಧಿ ಹೊಂದುತ್ತದೆ.\"",
      pending: "ಬಾಕಿ ಇದೆ",
      shipped: "ರವಾನಿಸಲಾಗಿದೆ",
      completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
      ordersTitle: "ಗ್ರಾಹಕರ ಆರ್ಡರ್‌ಗಳು",
      ordersSub: "ಇಂಡಿಯಾ ಪೋಸ್ಟ್ ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಮೂಲಕ ಖರೀದಿದಾರರಿಗೆ ನೇರವಾಗಿ ಆರ್ಡರ್‌ಗಳನ್ನು ರವಾನಿಸಿ",
      listenRequest: "ಗ್ರಾಹಕರ ವಿನಂತಿ ಆಲಿಸಿ",
      shipPackageBtn: "ಕೋರಿಯರ್ ಮಾಡಿ",
      markDeliveredBtn: "ತಲುಪಿದೆ",
      paidDelivered: "ಪಾವತಿಸಲಾಗಿದೆ ಮತ್ತು ತಲುಪಿಸಲಾಗಿದೆ",
      availablePayout: "ಖಾತೆಗೆ ವರ್ಗಾಯಿಸಲು ಲಭ್ಯವಿದೆ",
      linkedBank: "ಸಂಪರ್ಕಿತ ಬ್ಯಾಂಕ್ ಖಾತೆ",
      lifetimeOverview: "ಒಟ್ಟು ಮಾರಾಟದ ವಿವರ",
      withdrawHistory: "ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ ಮತ್ತು ವಹಿವಾಟು ಇತಿಹಾಸ",
      withdrawBtn: "ಬ್ಯಾಂಕ್‌ಗೆ ವರ್ಗಾಯಿಸಿ",
      sikhoTitle: "ಕಲಿಯಿರಿ (ಸಿಖೋ)",
      sikhoSub: "ಫೋಟೋಗಳು, ಪ್ಯಾಕೇಜಿಂಗ್ ಮತ್ತು ಬೆಲೆ ನಿಗದಿಯನ್ನು ಸುಧಾರಿಸಲು ನಿಮ್ಮದೇ ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಪಾಠಗಳು",
      bazaarTitle: "ಬಜಾರ್ (ನಿಮ್ಮ ದಾಸ್ತಾನು)",
      bazaarSub: "ಜಾಗತಿಕ ಮಳಿಗೆಯಲ್ಲಿ ಉತ್ಪನ್ನಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ ಮತ್ತು ದಾಸ್ತಾನು ನಿರ್ವಹಿಸಿ",
      addCraftBtn: "ಹೊಸ ಕಲೆ ಸೇರಿಸಿ",
      stockQuantity: "ದಾಸ್ತಾನು ಸಂಖ್ಯೆ",
      availableUnits: "ಲಭ್ಯವಿರುವ ವಸ್ತುಗಳು",
      outOfStock: "ದಾಸ್ತಾನು ಮುಗಿದಿದೆ",
      bankName: "ಬ್ಯಾಂಕ್ ಹೆಸರು",
      holderName: "ಖಾತೆದಾರರ ಹೆಸರು",
      accNumber: "ಖಾತೆ ಸಂಖ್ಯೆ",
      ifscCode: "IFSC ಕೋಡ್",
      payoutVerify: "ಹಣ ವರ್ಗಾವಣೆ ಪರಿಶೀಲನೆ",
      connectingSbi: "SBI ಗೇಟ್‌ವೇಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...",
      transSuccessful: "ವರ್ಗಾವಣೆ ಯಶಸ್ವಿಯಾಗಿದೆ!",
      sbiRef: "SBI ರೆಫರೆನ್ಸ್ ಸಂಖ್ಯೆ",
      doneBtn: "ಮುಗಿಯಿತು",
      confirmTrans: "ವರ್ಗಾವಣೆ ಖಚಿತಪಡಿಸಿ",
      recordingDesc: "ರೆಕಾರ್ಡಿಂಗ್ ಆಗುತ್ತಿದೆ...",
      voiceDescBtn: "ಧ್ವನಿ ವಿವರಣೆ",
      listNewCraft: "ಹೊಸ ಕರಕುಶಲ ವಸ್ತು ಸೇರಿಸಿ",
      instantShow: "ನಿಮ್ಮ ಕರಕುಶಲ ವಸ್ತು ತಕ್ಷಣವೇ ಗ್ರಾಹಕರಿಗೆ ಕಾಣಿಸುತ್ತದೆ",
      craftName: "ಕಲೆಯ ಹೆಸರು",
      categoryLabel: "ವರ್ಗ",
      priceLabel: "ಬೆಲೆ (₹)",
      stockLabel: "ದಾಸ್ತಾನು ಪ್ರಮಾಣ",
      descriptionLabel: "ವಿವರಣೆ",
      selectPicLabel: "ಚಿತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
      cancelBtn: "ರದ್ದುಮಾಡಿ",
      addCraftSubmit: "ಕಲೆ ಸೇರಿಸಿ",
      lessonsHeader: "ಕಲಿಯಿರಿ (ಸಿಖೋ)",
      lessonsSubText: "ಫೋಟೋಗಳು, ಪ್ಯಾಕೇಜಿಂಗ್ ಮತ್ತು ಬೆಲೆ ನಿಗದಿಯನ್ನು ಸುಧಾರಿಸಲು ನಿಮ್ಮದೇ ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಪಾಠಗಳು",
      lessonPhotography: "ಪಾಠ 1 • ಛಾಯಾಗ್ರಹಣ",
      lessonLogistics: "ಪಾಠ 2 • ಪ್ಯಾಕೇಜಿಂಗ್",
      lessonCourier: "ಪಾಠ 3 • ಪೋಸ್ಟಲ್ ಕೊರಿಯರ್",
      lessonBusiness: "ಪಾಠ 4 • ವ್ಯಾಪಾರ ಮೂಲಭೂತ ಅಂಶಗಳು",
      lowInternet: "ಕಡಿಮೆ ಇಂಟರ್ನೆಟ್ ಮೋಡ್",
      lowInternetSub: "ಡೇಟಾ ಉಳಿಸಲು ಕೇವಲ ಆಡಿಯೋ ಚಾಲನೆಯಲ್ಲಿದೆ. ಕನ್ನಡ ವಿವರಣೆ ಸಕ್ರಿಯವಾಗಿದೆ.",
      markDone: "ಪಾಠ ಮುಗಿಸಿ"
    },
    sellerOnboarding: {
      welcomeTitle: "ಕಾರೀಘರ್‌ಗೆ ಸುಸ್ವಾಗತ",
      welcomeSubtitle: "\"ನಿಮ್ಮ ಕಲೆಯನ್ನು ನೇರವಾಗಿ ಮನೆಯಿಂದಲೇ ಮಾರಿ.\"",
      newHere: "ನಾನು ಇಲ್ಲಿ ಹೊಸಬರು",
      haveAccount: "ನನ್ನ ಬಳಿ ಖಾತೆ ಇದೆ →",
      voiceWelcome: "\"ಸುಸ್ವಾಗತ. ನಿಮ್ಮ ಕರಕುಶಲ ವಸ್ತುಗಳನ್ನು ಮಾರಾಟ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಲು 'ನಾನು ಇಲ್ಲಿ ಹೊಸಬರು' ಎಂಬುದನ್ನು ಒತ್ತಿರಿ.\"",
      browseCustomer: "ಗ್ರಾಹಕರಾಗಿ ಬ್ರೌಸ್ ಮಾಡಿ",
      consumerStore: "ಗ್ರಾಹಕರ ಮಳಿಗೆ",
      namasteSister: "\"ನಮಸ್ತೆ ಸಹೋದರಿ, ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸೋಣ.\"",
      tellName: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮಗೆ ತಿಳಿಸಿ",
      fullName: "ಪೂರ್ಣ ಹೆಸರು",
      placeholderName: "ಉದಾಹರಣೆಗೆ: ರಾಧಾ ದೇವಿ",
      speakOrType: "ಮೈಕ್ರೊಫೋನ್‌ನಲ್ಲಿ ಸ್ಪಷ್ಟವಾಗಿ ಮಾತನಾಡಿ ಅಥವಾ ಕೀಬೋರ್ಡ್ ಬಳಸಿ ನಿಮ್ಮ ಹೆಸರನ್ನು ಟೈಪ್ ಮಾಡಿ.",
      next: "ಮುಂದೆ ಹೋಗಿ →",
      needHelpWatch: "ಸಹಾಯ ಬೇಕೇ? ವೀಕ್ಷಿಸಿ: ಕಾರೀಘರ್ ಅನ್ನು ಹೇಗೆ ಬಳಸುವುದು",
      voiceGuidanceStep1: "ಬನ್ನಿ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ರಚಿಸೋಣ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ತಿಳಿಸಿ.",
      createSecretCode: "ನಿಮ್ಮ ರಹಸ್ಯ ಕೋಡ್ ರಚಿಸಿ",
      rememberCode: "\"ನಿಮಗೆ ಯಾವಾಗಲೂ ನೆನಪಿರುವಂತಹ ಕೋಡ್ ಅನ್ನು ಇರಿಸಿ\"",
      secretCodeLabel: "ರಹಸ್ಯ ಕೋಡ್ (ಪಾಸ್ವರ್ಡ್)",
      placeholderCode: "ಉದಾಹರಣೆಗೆ: 1234",
      aageBadhein: "ಮುಂದೆ ಹೋಗಿ →",
      listening: "ನಾನು ಕೇಳುತ್ತಿದ್ದೇನೆ...",
      watchTypeCode: "ವೀಕ್ಷಿಸಿ: ನಿಮ್ಮ ಕೋಡ್ ಅನ್ನು ಹೇಗೆ ಟೈಪ್ ಮಾಡುವುದು",
      empoweringArtisansDesc: "ಕಲೆ ಮತ್ತು ಕೋಡ್: ಕುಶಲಕರ್ಮಿಗಳ ಸಬಲೀಕರಣ — ಹೆರಿಟೇಜ್ ಹರ್ತ್ ಆಪ್ ಅನ್ನು ಹೇಗೆ ಬಳಸುವುದು ಎಂದು ತಿಳಿಯಿರಿ!",
      voiceGuidanceStep2: "ನಿಮಗೆ ನೆನಪಿರುವಂತಹ ಒಂದು ಸರಳ ಕೋಡ್ ಅನ್ನು ಆರಿಸಿ. ನಾನು ಇದನ್ನು ಸುರಕ್ಷಿತವಾಗಿಡುತ್ತೇನೆ.",
      whereAreYouFrom: "ನೀವು ಎಲ್ಲಿಂದ ಬಂದಿದ್ದೀರಿ?",
      enterPhoneLocation: "\"ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ಮತ್ತು ಸ್ಥಳವನ್ನು ತಿಳಿಸಿ\"",
      voiceGuidanceStep3: "\"ಗ್ರಾಹಕರು ನಿಮ್ಮನ್ನು ಹುಡುಕಲು ಅನುಕೂಲವಾಗುವಂತೆ ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ಮತ್ತು ನಗರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.\"",
      phoneNumberLabel: "ಫೋನ್ ಸಂಖ್ಯೆ",
      stateLabel: "ರಾಜ್ಯ",
      districtLabel: "ಜಿಲ್ಲೆ",
      selectState: "— ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ —",
      selectDistrict: "— ಜಿಲ್ಲೆ ಆಯ್ಕೆಮಾಡಿ —",
      empoweringArtisansTitle: "ಕಲೆ ಮತ್ತು ಕೋಡ್: ಕುಶಲಕರ್ಮಿಗಳ ಸಬಲೀಕರಣ",
      welcomeBackSister: "\"ಸ್ವಾಗತ ಸಹೋದರಿ. ನಿಮ್ಮ ಕಲೆಯು ನಮಗೆಲ್ಲರಿಗೂ ಸ್ಫೂರ್ತಿಯಾಗಿದೆ.\"",
      enterNamePass: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರು ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ.",
      loginLabel: "ಲಾಗಿನ್ ಮಾಡಿ →"
    },
    chatbot: {
      tooltipText: "ಯಾವುದೇ समस्या ಎದುರಾಗಿದೆಯೇ?",
      tooltipSub: "ನನ್ನನ್ನು ಒತ್ತಿರಿ, ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ! ❀",
      onlineSupport: "ಆನ್‌ಲೈನ್ ಮತ್ತು ಮಾರ್ಗದರ್ಶಿತ ಬೆಂಬಲ",
      assistantName: "ಕಾರೀಘರ್ ಸಹಾಯಕ",
      inputPlaceholder: "ಪ್ರಶ್ನೆ ಕೇಳಿ...",
      footerBranding: "ಭಾರತೀಯ ಕಲೆಯ ಸಂರಕ್ಷಣೆ • ಕಾರೀಘರ್ ಸಂಗಾತಿ",
      introDefault: "ನಮಸ್ತೆ! ನಾನು ನಿಮ್ಮ ಕಾರೀಘರ್ ಡಿಜಿಟಲ್ ಸಂಗಾತಿ. ಇಂದು ನಮ್ಮ ಕುಶಲಕರ್ಮಿಗಳ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ? ❀",
      introHome: "ಕಾರೀಘರ್‌ಗೆ ಸುಸ್ವಾಗತ! ನಮ್ಮ ಕುಶಲಕರ್ಮಿಗಳ ಕಥೆಗಳ ಬಗ್ಗೆ ತಿಳಿಸಲು, ಸಾಂಪ್ರದಾಯಿಕ ವರ್ಗಗಳನ್ನು ಅನ್ವೇಷಿಸಲು ಅಥವಾ ನಮ್ಮ ನ್ಯಾಯೋಚಿತ ವ್ಯಾಪಾರ ಮಾದರಿಯನ್ನು ವಿವರಿಸಲು ನಾನು ಸಹಾಯ ಮಾಡಬಲ್ಲೆ. ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ? ❀",
      introCategories: "ನಮ್ಮ ಕಲಾ ಸಂಗ್ರಹವನ್ನು ಅನ್ವೇಷಿಸುತ್ತಿದ್ದೀರಾ? ನೀವು ಭಾರತದ ನಿರ್ದಿಷ್ಟ ಜಿಲ್ಲೆಗಳ ಆಧಾರದ ಮೇಲೆ ಫಿಲ್ಟರ್ ಮಾಡಬಹುದು ಅಥವಾ ನಿಮ್ಮ ಬಜೆಟ್‌ಗೆ ಅನುಗುಣವಾಗಿ ಬೆಲೆ ಶ್ರೇಣಿಯನ್ನು ಹೊಂದಿಸಬಹುದು. ಯಾವುದಾದರೂ ಹೊಸ ವಸ್ತುಗಳನ್ನು ಹುಡುಕಲು ಸಹಾಯ ಬೇಕೇ? ❀",
      introProduct: "ಈ ಪಾರಂಪರಿಕ ಕಲಾಕೃತಿಯನ್ನು ಪ್ರಾದೇಶಿಕ ನೈಸರ್ಗಿಕ ವಸ್ತುಗಳಿಂದ ಕೈಯಿಂದಲೇ ತಯಾರಿಸಲಾಗಿದೆ! ನೀವು 3-ಹಂತದ ಕರಕುಶಲ ತಯಾರಿಕೆಯ ಪ್ರಕ್ರಿಯೆಯನ್ನು ತಿಳಿಯಲು ಅಥವಾ ಶಿಪ್ಪಿಂಗ್ ಸುರಕ್ಷತೆಯನ್ನು ಪರಿಶೀಲಿಸಲು ಬಯಸುವಿರಾ? ❀",
      introSeller: "ನಮಸ್ತೆ ಪಾಲುದಾರರೇ! ನಿಮ್ಮ ಕುಶಲಕರ್ಮಿಗಳ ಕಾರ್ಯಕ್ಷೇತ್ರದಲ್ಲಿ, ನಮ್ಮ ನ್ಯಾಯಯುತ ಬೆಲೆ ನಿಗದಿ ಉಪಕರಣವನ್ನು ಬಳಸಿ ಪ್ರಾದೇಶಿಕ ಜೀವನ ವೇತನವನ್ನು ಲೆಕ್ಕ ಹಾಕಬಹುದು, ನೇರ ವಾಟ್ಸಾಪ್ ಚಾಟ್ ಲಿಂಕ್‌ಗಳನ್ನು ರಚಿಸಬಹುದು ಅಥವಾ ಧ್ವನಿ ವಿವರಣೆಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಬಹುದು. ಸಹಾಯ ಬೇಕೇ? ❀",
      introHelp: "ನೀವು ಸಹಾಯ ಕೇಂದ್ರಕ್ಕೆ ತಲುಪಿದ್ದೀರಿ! ನಾನು ಕನ್ನಡ, ಹಿಂದಿ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧನಾಗಿದ್ದೇನೆ. ಕೆಳಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ತಕ್ಷಣದ ಉತ್ತರಕ್ಕಾಗಿ ಚಿಪ್ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ! ❀",
      introLogin: "ನಮ್ಮ ನಮಸ್ತೆ ದೃಢೀಕರಣ ಫಲಕಕ್ಕೆ ಸುಸ್ವಾಗತ! ನೀವು ಗ್ರಾಹಕರಾಗಿ ಅಥವಾ ಮಾರಾಟಗಾರರಾಗಿ ಸುಲಭವಾಗಿ ನೋಂದಾಯಿಸಿಕೊಳ್ಳಬಹುದು, ಪ್ರೊಫೈಲ್ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಬಹುದು ಮತ್ತು ಪರಿಶೀಲಿಸಲು '1234' ಒಟಿಪಿ ನಮೂದಿಸಬಹುದು. ❀",
      ackHindi: "ನಮಸ್ತೆ! ಈಗ ನಾನು ಹಿಂದಿಯಲ್ಲಿ ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧನಾಗಿದ್ದೇನೆ. ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಬಹುದು. ❀",
      ackEnglish: "ಉತ್ತಮ! ಈಗ ನಾನು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧನಾಗಿದ್ದೇನೆ. ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ? ❀",
      ackKannada: "ನಮಸ್ತೆ! ಈಗ ನಾನು ಕನ್ನಡದಲ್ಲಿ ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧನಾಗಿದ್ದೇನೆ. ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಬಹುದು. ❀",
      errorMsg: "ನಮಸ್ತೆ! ಸಂಪರ್ಕ ಸಾಧಿಸಲು ತೊಂದರೆಯಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ಸಹಾಯ ಪುಟದಲ್ಲಿರುವ ಪ್ರಶ್ನೋತ್ತರಗಳನ್ನು ಅನ್ವೇಷಿಸಿ. 🙏",
      chips: {
        livingWage: "ಜೀವನ ವೇತನ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
        whatsapp: "ವಾಟ್ಸಾಪ್ ಚಾಟ್ ಸೆಟಪ್",
        voiceRec: "ಧ್ವನಿ ರೆಕಾರ್ಡರ್ ನೆರವು",
        howOrder: "ಆರ್ಡರ್ ಮಾಡುವುದು ಹೇಗೆ?",
        directFair: "ನೇರ ನ್ಯಾಯೋಚಿತ ವ್ಯಾಪಾರ?",
        meetArtisans: "ನಮ್ಮ ಕುಶಲಕರ್ಮಿಗಳನ್ನು ಭೇಟಿ ಮಾಡಿ",
        fragileShip: "ಸೂಕ್ಷ್ಮ ವಸ್ತುಗಳ ಶಿಪ್ಪಿಂಗ್",
        loomWeave: "ನೇಯ್ಗೆ ಪ್ರಕ್ರಿಯೆ",
        reviewGuide: "ವಿಮರ್ಶೆ ಮಾರ್ಗಸೂಚಿಗಳು",
        genGuide: "ಸಾಮಾನ್ಯ ವೆಬ್‌ಸೈಟ್ ಮಾರ್ಗದರ್ಶಿ",
        otpVerify: "ಒಟಿಪಿ ಪರಿಶೀಲನೆ",
        packagingStd: "ಪ್ಯಾಕೇಜಿಂಗ್ ಗುಣಮಟ್ಟ"
      }
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('karighar_language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('karighar_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  const t = (key) => {
    const keys = key.split('.');
    let result = translations[language];
    for (const k of keys) {
      if (result && result[k] !== undefined) {
        result = result[k];
      } else {
        return key; // fallback to key itself
      }
    }
    return result;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
