/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MatchmakerRouteImport } from './routes/matchmaker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BarterRouteImport } from './routes/barter'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrderSuccessIdRouteImport } from './routes/order-success.$id'
import { Route as CertificateIdRouteImport } from './routes/certificate.$id'
import { Route as ArtisansIdRouteImport } from './routes/artisans.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakerRoute = MatchmakerRouteImport.update({
  id: '/matchmaker',
  path: '/matchmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BarterRoute = BarterRouteImport.update({
  id: '/barter',
  path: '/barter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const OrderSuccessIdRoute = OrderSuccessIdRouteImport.update({
  id: '/order-success/$id',
  path: '/order-success/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansIdRoute = ArtisansIdRouteImport.update({
  id: '/artisans/$id',
  path: '/artisans/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/barter': typeof BarterRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRoute
  '/network': typeof NetworkRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/signup': typeof SignupRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/barter': typeof BarterRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRoute
  '/network': typeof NetworkRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/signup': typeof SignupRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/barter': typeof BarterRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRoute
  '/network': typeof NetworkRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/signup': typeof SignupRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/barter'
    | '/checkout'
    | '/community'
    | '/impact'
    | '/join'
    | '/learn'
    | '/login'
    | '/matchmaker'
    | '/network'
    | '/products'
    | '/profile'
    | '/seller'
    | '/signup'
    | '/artisans/$id'
    | '/certificate/$id'
    | '/order-success/$id'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/barter'
    | '/checkout'
    | '/community'
    | '/impact'
    | '/join'
    | '/learn'
    | '/login'
    | '/matchmaker'
    | '/network'
    | '/products'
    | '/profile'
    | '/seller'
    | '/signup'
    | '/artisans/$id'
    | '/certificate/$id'
    | '/order-success/$id'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/barter'
    | '/checkout'
    | '/community'
    | '/impact'
    | '/join'
    | '/learn'
    | '/login'
    | '/matchmaker'
    | '/network'
    | '/products'
    | '/profile'
    | '/seller'
    | '/signup'
    | '/artisans/$id'
    | '/certificate/$id'
    | '/order-success/$id'
    | '/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BarterRoute: typeof BarterRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  ImpactRoute: typeof ImpactRoute
  JoinRoute: typeof JoinRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MatchmakerRoute: typeof MatchmakerRoute
  NetworkRoute: typeof NetworkRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SellerRoute: typeof SellerRoute
  SignupRoute: typeof SignupRoute
  ArtisansIdRoute: typeof ArtisansIdRoute
  CertificateIdRoute: typeof CertificateIdRoute
  OrderSuccessIdRoute: typeof OrderSuccessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaker': {
      id: '/matchmaker'
      path: '/matchmaker'
      fullPath: '/matchmaker'
      preLoaderRoute: typeof MatchmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barter': {
      id: '/barter'
      path: '/barter'
      fullPath: '/barter'
      preLoaderRoute: typeof BarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/order-success/$id': {
      id: '/order-success/$id'
      path: '/order-success/$id'
      fullPath: '/order-success/$id'
      preLoaderRoute: typeof OrderSuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans/$id': {
      id: '/artisans/$id'
      path: '/artisans/$id'
      fullPath: '/artisans/$id'
      preLoaderRoute: typeof ArtisansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BarterRoute: BarterRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  ImpactRoute: ImpactRoute,
  JoinRoute: JoinRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MatchmakerRoute: MatchmakerRoute,
  NetworkRoute: NetworkRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SellerRoute: SellerRoute,
  SignupRoute: SignupRoute,
  ArtisansIdRoute: ArtisansIdRoute,
  CertificateIdRoute: CertificateIdRoute,
  OrderSuccessIdRoute: OrderSuccessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
