tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-surface-variant": "#414752",
        "primary-container": "#1976d2",
        "on-surface": "#191c1e",
        "primary": "#005dac",
        "outline-variant": "#c1c6d4",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#a0f399",
        "surface": "#f7f9fb",
        "outline": "#717783",
        "on-secondary-container": "#217128",
        "surface-container-lowest": "#ffffff",
        "secondary": "#1b6d24",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "background": "#f7f9fb",
        "error-container": "#ffdad6",
        "tertiary": "#505e68",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "32px",
        "sidebar-width": "280px",
        "margin-mobile": "16px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-md": ["Lexend", "sans-serif"],
        "headline-lg": ["Lexend", "sans-serif"],
        "headline-xl": ["Lexend", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
};
