export type SiteLocale = "en" | "hi" | "mr" | "kn" | "ta" | "te";

export const supportedLanguages: Array<{ value: SiteLocale; label: string }> = [
  { value: "en", label: "English" },
  { value: "hi", label: "हिन्दी" },
  { value: "mr", label: "मराठी" },
  { value: "kn", label: "ಕನ್ನಡ" },
  { value: "ta", label: "தமிழ்" },
  { value: "te", label: "తెలుగు" },
];

export const siteCopy: Record<string, any> = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      features: "Features",
      blog: "Blog",
      dashboard: "Dashboard",
      chat: "Chat",
      journal: "Journal",
      assessments: "Assessments",
      appointments: "Appointments",
      patients: "Patients",
      registerPatient: "Register patient",
      mobile: "Mobile navigation",
      sidebar: "Section navigation",
      calmMode: "Calm, privacy-first workspace",
      signIn: "Sign In",
      getStarted: "Get Started",
      profile: "Profile",
      wellness: "My Wellness",
      chatHistory: "Chat History",
      settings: "Settings",
      signOut: "Sign Out",
      language: "Switch language",
      support: "Support",
      navigation: "Navigation",
      social: "Social",
      legal: "Legal",
    },
    hero: {
      badge: "AI-Powered Wellness",
      title1: "Compassionate AI",
      title2: "Support",
      title3: "in Your",
      title4: "Native Language.",
      subtitle:
        "AI-powered multilingual emotional wellness assistance for rural and underserved communities - private, safe, and always available.",
      trust: ["End-to-End Encrypted", "No Account Required", "Works on Low Bandwidth"],
      start: "Begin Your Journey",
      learn: "Learn more",
      availableIn: "Available in:",
      languages: ["English", "हिन्दी", "मराठी", "ಕನ್ನಡ", "தமிழ்"],
      live: "Live",
      voice: "Voice Support",
      voiceBody: "Speak in Hindi, Marathi, Kannada, Tamil, or English",
      private: "Fully Private",
      privateBody: "End-to-end encrypted. Your conversations are never shared.",
      whatsapp: "WhatsApp Support",
      whatsappBody: "Chat via WhatsApp - no app needed",
      stats: [
        { value: "5+", label: "Languages" },
        { value: "10K+", label: "Users Supported" },
        { value: "24/7", label: "Availability" },
      ],
      sampleUser: "I feel very tired today.",
      sampleReply: "I understand. Would you like to tell me more?",
    },
    about: {
      lead: "Mental health",
      title1: "understanding,",
      title2: "care and",
      title3: "your priority.",
      body1: "Just as you take care of your body, your mind also deserves complete care and understanding.",
      body2:
        "Saathi bridges the gap between rural communities and professional mental wellness support - available in your language, at any hour, completely private.",
    },
    mood: {
      title1: "How Are",
      title2: "You",
      title3: "Feeling",
      title4: "Today?",
      moods: {
        happy: "That's wonderful! Your joy lights up the room. ✨",
        angry: "It's okay to feel this way. Let's breathe through it together.",
        good: "Great to hear! Keep nurturing that positive energy.",
        calm: "A calm mind is your greatest strength. 🌊",
        sad: "We're here for you. You're never alone in this. 💙",
      },
      tabs: [
        { id: "wellness", emoji: "🌸", title: "Wellness", subtitle: "Simple habits to keep your mental health strong." },
        { id: "mindfulness", emoji: "🧠", title: "Mindfulness", subtitle: "Meditation practices for everyday life." },
        { id: "habits", emoji: "🔄", title: "Habits", subtitle: "The power of routine in mental health." },
      ],
    },
    features: {
      title1: "Everything You",
      title2: "Need For",
      title3: "Your",
      title4: "Wellness Journey",
      cta: "Get Help Now",
      services: [
        {
          badgeText: "24/7 Support",
          title: "Call Services",
          description: "Get instant access to compassionate, human-in-the-loop support calls anytime you need to talk.",
          ctaText: "Start a call",
        },
        {
          badgeText: "AI Companion",
          title: "Personalized Chatbot",
          description: "Converse with our intelligent AI companion, designed to adapt specifically to your emotional state.",
          ctaText: "Chat now",
        },
        {
          badgeText: "Self Care",
          title: "Mood Tracking + Screening",
          description: "Monitor your daily emotions and screen for key wellness trends securely and privately.",
          ctaText: "Check mood",
        },
        {
          badgeText: "Verified Care",
          title: "Instant Communication",
          description: "Locate and connect with professional mental health specialists near your geographical area.",
          ctaText: "Find doctors",
        },
        {
          badgeText: "Universal Access",
          title: "Multilingual Support",
          description: "Receive tailored mental wellness materials and AI conversation in your preferred native language.",
          ctaText: "Change language",
        },
      ],
    },
    blog: {
      title1: "Recent",
      title2: "Mental Health",
      title3: "Articles & Insights",
      intro:
        "Explore practical clinical guidance, mental wellness strategies, and scientific findings from our team of verified experts.",
      articles: [
        {
          headline: "Nurturing Mindfulness in Daily Life",
          excerpt:
            "Discover simple, practical techniques to cultivate deep presence, reduce daily work stress, and restore emotional stability in under five minutes a day.",
          tag: "Mindfulness",
          writer: "Dr. Ananya Sen",
        },
        {
          headline: "Understanding Stress: A Compassionate Guide",
          excerpt:
            "Stress is a natural indicator, not a failure. Learn how to map your physical stress triggers and respond to them with kindness and healthy routines.",
          tag: "Self-Care",
          writer: "Siddharth Mehta",
        },
        {
          headline: "The Importance of Emotional Screening",
          excerpt:
            "Why regular self-assessments and emotional tracking are the cornerstones of long-term psychological resilience. Demystified with the latest clinical data.",
          tag: "Mental Health",
          writer: "Dr. Kabir Roy",
        },
      ],
    },
    footer: {
      title1: "Rethink your",
      title2: "Benefits",
      title3: "of",
      title4: "Meditation",
      intro: "Benefits of meditation, think about it. If you don't want to, we can do it for you.",
      subscribe: "Subscribe",
      email: "Enter your email",
      supportTitle: "Support",
      navTitle: "Navigation",
      supportLinks: ["Support", "Help Center", "Contact Us", "FAQ"],
      navLinks: [
        { label: "Home", href: "/" },
        { label: "Specialists", href: "#specialists" },
        { label: "Blog", href: "#blog" },
      ],
      socialLinks: ["Instagram", "Twitter", "LinkedIn"],
      legalLinks: ["Privacy Policy", "Terms Of Use"],
      copyright: "© 2026 Saathi. All rights reserved.",
      brand: "Compassionate AI support in your native language.",
    },
  },
  hi: {
    nav: {
      home: "मुखपृष्ठ",
      about: "परिचय",
      features: "विशेषताएँ",
      blog: "ब्लॉग",
      dashboard: "डैशबोर्ड",
      chat: "चैट",
      journal: "जर्नल",
      assessments: "आकलन",
      appointments: "अपॉइंटमेंट",
      patients: "मरीज",
      registerPatient: "मरीज पंजीकृत करें",
      mobile: "मोबाइल नेविगेशन",
      sidebar: "सेक्शन नेविगेशन",
      calmMode: "शांत, गोपनीय-प्रथम कार्यक्षेत्र",
      signIn: "साइन इन",
      getStarted: "शुरू करें",
      profile: "प्रोफ़ाइल",
      wellness: "मेरी भलाई",
      chatHistory: "चैट इतिहास",
      settings: "सेटिंग्स",
      signOut: "साइन आउट",
      language: "भाषा बदलें",
      support: "सहायता",
      navigation: "नेविगेशन",
      social: "सोशल",
      legal: "कानूनी",
    },
    hero: {
      badge: "एआई-संचालित भलाई",
      title1: "करुणामय एआई",
      title2: "सहारा",
      title3: "आपकी",
      title4: "मातृभाषा में।",
      subtitle:
        "ग्रामीण और कम-सुविधा वाले समुदायों के लिए बहुभाषी भावनात्मक भलाई सहायता - निजी, सुरक्षित और हर समय उपलब्ध।",
      trust: ["एंड-टू-एंड एन्क्रिप्टेड", "खाते की आवश्यकता नहीं", "कम बैंडविड्थ पर भी काम करता है"],
      start: "अपनी यात्रा शुरू करें",
      learn: "और जानें",
      availableIn: "उपलब्ध भाषाएँ:",
      languages: ["English", "हिन्दी", "मराठी", "ಕನ್ನಡ", "தமிழ்"],
      live: "लाइव",
      voice: "आवाज़ सहायता",
      voiceBody: "हिन्दी, मराठी, कन्नड़, तमिल या अंग्रेज़ी में बोलें",
      private: "पूरी तरह निजी",
      privateBody: "एंड-टू-एंड एन्क्रिप्टेड। आपकी बातचीत कभी साझा नहीं की जाती।",
      whatsapp: "व्हाट्सऐप सहायता",
      whatsappBody: "व्हाट्सऐप के माध्यम से चैट करें - ऐप की आवश्यकता नहीं",
      stats: [
        { value: "5+", label: "भाषाएँ" },
        { value: "10K+", label: "उपयोगकर्ता समर्थित" },
        { value: "24/7", label: "उपलब्धता" },
      ],
      sampleUser: "मुझे आज बहुत थकान हो रही है।",
      sampleReply: "मैं समझता हूँ। क्या आप मुझे और बताएंगे?",
    },
    about: {
      lead: "मानसिक स्वास्थ्य",
      title1: "समझ,",
      title2: "देखभाल और",
      title3: "आपकी प्राथमिकता।",
      body1: "जैसे आप अपने शरीर का ध्यान रखते हैं, वैसे ही आपके मन को भी पूरी देखभाल और समझ चाहिए।",
      body2:
        "साथी ग्रामीण समुदायों और पेशेवर मानसिक भलाई सहायता के बीच की दूरी को पाटता है - आपकी भाषा में, किसी भी समय, पूरी तरह निजी।",
    },
    mood: {
      title1: "आप",
      title2: "कैसा",
      title3: "महसूस",
      title4: "कर रहे हैं?",
      moods: {
        happy: "बहुत बढ़िया! आपकी खुशी सबका दिन रोशन करती है। ✨",
        angry: "ऐसा महसूस करना ठीक है। चलिए साथ में साँस लेते हैं।",
        good: "अच्छा लगा सुनकर! उस सकारात्मक ऊर्जा को बनाए रखें।",
        calm: "शांत मन आपकी सबसे बड़ी ताकत है। 🌊",
        sad: "हम आपके साथ हैं। आप अकेले नहीं हैं। 💙",
      },
      tabs: [
        { id: "wellness", emoji: "🌸", title: "भलाई", subtitle: "मानसिक स्वास्थ्य को मजबूत रखने की सरल आदतें।" },
        { id: "mindfulness", emoji: "🧠", title: "सजगता", subtitle: "रोज़मर्रा के लिए ध्यान अभ्यास।" },
        { id: "habits", emoji: "🔄", title: "आदतें", subtitle: "मानसिक स्वास्थ्य में दिनचर्या की ताकत।" },
      ],
    },
    features: {
      title1: "आपकी",
      title2: "ज़रूरत की हर चीज़",
      title3: "आपकी",
      title4: "भलाई यात्रा के लिए",
      cta: "अभी सहायता लें",
      services: [
        { badgeText: "24/7 सहायता", title: "कॉल सेवाएँ", description: "जब भी बात करनी हो, तुरंत सहानुभूतिपूर्ण मानव-समर्थित कॉल सहायता पाएँ।", ctaText: "कॉल शुरू करें" },
        { badgeText: "एआई साथी", title: "व्यक्तिगत चैटबॉट", description: "एक बुद्धिमान एआई साथी के साथ बात करें जो आपकी भावनात्मक स्थिति के अनुसार ढलता है।", ctaText: "अभी चैट करें" },
        { badgeText: "स्व-देखभाल", title: "मूड ट्रैकिंग + स्क्रीनिंग", description: "अपनी दैनिक भावनाओं को ट्रैक करें और भलाई के रुझानों की निजी रूप से जाँच करें।", ctaText: "मूड जाँचें" },
        { badgeText: "सत्यापित देखभाल", title: "तुरंत संपर्क", description: "अपने क्षेत्र के पास मानसिक स्वास्थ्य विशेषज्ञों को खोजें और उनसे जुड़ें।", ctaText: "डॉक्टर खोजें" },
        { badgeText: "सार्वभौमिक पहुँच", title: "बहुभाषी सहायता", description: "अपनी पसंदीदा भाषा में अनुकूलित भलाई सामग्री और एआई बातचीत पाएँ।", ctaText: "भाषा बदलें" },
      ],
    },
    blog: {
      title1: "हाल के",
      title2: "मानसिक स्वास्थ्य",
      title3: "लेख और अंतर्दृष्टि",
      intro: "हमारी प्रमाणित विशेषज्ञ टीम से उपयोगी चिकित्सीय मार्गदर्शन, भलाई की रणनीतियाँ और वैज्ञानिक जानकारी पढ़ें।",
      articles: [
        { headline: "दैनिक जीवन में सजगता को पोषित करना", excerpt: "कुछ ही मिनटों में मौजूदगी बढ़ाने, तनाव घटाने और भावनात्मक स्थिरता वापस पाने की सरल तकनीकें जानें।", tag: "सजगता", writer: "डॉ. अनन्या सेन" },
        { headline: "तनाव को समझना: करुणामय मार्गदर्शिका", excerpt: "तनाव असफलता नहीं, एक संकेत है। अपने तनाव ट्रिगर पहचानें और करुणा के साथ प्रतिक्रिया दें।", tag: "स्व-देखभाल", writer: "सिद्धार्थ मेहता" },
        { headline: "भावनात्मक स्क्रीनिंग का महत्व", excerpt: "नियमित आत्म-मूल्यांकन और भावनात्मक ट्रैकिंग दीर्घकालिक मानसिक दृढ़ता की नींव क्यों हैं।", tag: "मानसिक स्वास्थ्य", writer: "डॉ. कबीर रॉय" },
      ],
    },
    footer: {
      title1: "पुनर्विचार करें",
      title2: "लाभ",
      title3: "का",
      title4: "ध्यान",
      intro: "ध्यान के लाभों पर विचार करें। अगर आप नहीं करना चाहते, तो हम आपके लिए कर सकते हैं।",
      subscribe: "सब्सक्राइब करें",
      email: "अपना ईमेल दर्ज करें",
      supportTitle: "सहायता",
      navTitle: "नेविगेशन",
      supportLinks: ["सहायता", "हेल्प सेंटर", "संपर्क करें", "FAQ"],
      navLinks: [
        { label: "मुखपृष्ठ", href: "/" },
        { label: "विशेषज्ञ", href: "#specialists" },
        { label: "ब्लॉग", href: "#blog" },
      ],
      socialLinks: ["इंस्टाग्राम", "ट्विटर", "लिंक्डइन"],
      legalLinks: ["गोपनीयता नीति", "उपयोग की शर्तें"],
      copyright: "© 2026 साथी. सर्वाधिकार सुरक्षित।",
      brand: "आपकी मातृभाषा में करुणामय एआई सहायता।",
    },
  },
  mr: {
    nav: {
      home: "मुखपृष्ठ",
      about: "परिचय",
      features: "वैशिष्ट्ये",
      blog: "ब्लॉग",
      dashboard: "डॅशबोर्ड",
      chat: "चॅट",
      journal: "जर्नल",
      assessments: "मूल्यांकन",
      appointments: "अपॉइंटमेंट्स",
      patients: "रुग्ण",
      registerPatient: "रुग्ण नोंदणी करा",
      mobile: "मोबाईल नेव्हिगेशन",
      sidebar: "विभाग नेव्हिगेशन",
      calmMode: "शांत, गोपनीयता-प्रथम कार्यक्षेत्र",
      signIn: "साइन इन",
      getStarted: "सुरू करा",
      profile: "प्रोफाइल",
      wellness: "माझे आरोग्य",
      chatHistory: "चॅट इतिहास",
      settings: "सेटिंग्ज",
      signOut: "साइन आउट",
      language: "भाषा बदला",
      support: "मदत",
      navigation: "नेव्हिगेशन",
      social: "सामाजिक",
      legal: "कायदेशीर",
    },
    hero: {
      badge: "एआय-चालित आरोग्य",
      title1: "करुणामय एआय",
      title2: "साथ",
      title3: "तुमच्या",
      title4: "मातृभाषेत.",
      subtitle:
        "ग्रामीण आणि कमी-सुविधा असलेल्या समुदायांसाठी बहुभाषिक भावनिक आरोग्य सहाय्य - खाजगी, सुरक्षित आणि नेहमी उपलब्ध.",
      trust: ["एंड-टू-एंड एन्क्रिप्टेड", "खात्याची गरज नाही", "कमी बँडविड्थवर चालते"],
      start: "तुमचा प्रवास सुरू करा",
      learn: "अधिक जाणून घ्या",
      availableIn: "उपलब्ध भाषा:",
      languages: ["English", "हिन्दी", "मराठी", "ಕನ್ನಡ", "தமிழ்"],
      live: "लाइव्ह",
      voice: "आवाज सहाय्य",
      voiceBody: "हिन्दी, मराठी, कन्नड, तमिळ किंवा इंग्रजीत बोला",
      private: "पूर्णपणे खाजगी",
      privateBody: "एंड-टू-एंड एन्क्रिप्टेड. तुमच्या संभाषणाची कधीही देवाणघेवाण केली जात नाही.",
      whatsapp: "व्हॉट्सॲप सहाय्य",
      whatsappBody: "व्हॉट्सॲपद्वारे चॅट करा - अॅपची गरज नाही",
      stats: [
        { value: "5+", label: "भाषा" },
        { value: "10K+", label: "वापरकर्ते समर्थित" },
        { value: "24/7", label: "उपलब्धता" },
      ],
      sampleUser: "मला आज खूप थकवा जाणवत आहे.",
      sampleReply: "मी समजतो. तुम्हाला आणखी सांगायचे आहे का?",
    },
    about: {
      lead: "मानसिक आरोग्य",
      title1: "समज,",
      title2: "काळजी आणि",
      title3: "तुमची प्राथमिकता.",
      body1: "जसे तुम्ही तुमच्या शरीराची काळजी घेता, तसेच तुमच्या मनालाही संपूर्ण काळजी आणि समज आवश्यक आहे.",
      body2:
        "साथी ग्रामीण समुदाय आणि व्यावसायिक मानसिक आरोग्य सहाय्य यांच्यातील दरी भरून काढतो - तुमच्या भाषेत, कधीही, पूर्णपणे खाजगी.",
    },
    mood: {
      title1: "तुम्हाला",
      title2: "कसे",
      title3: "वाटत",
      title4: "आहे आज?",
      moods: {
        happy: "छान! तुमचा आनंद सगळ्यांचा दिवस उजळून टाकतो. ✨",
        angry: "असे वाटणे ठीक आहे. चला एकत्र श्वास घेऊया.",
        good: "छान ऐकून आनंद झाला! ती सकारात्मक ऊर्जा टिकवून ठेवा.",
        calm: "शांत मन ही तुमची सर्वात मोठी ताकद आहे. 🌊",
        sad: "आम्ही तुमच्यासोबत आहोत. तुम्ही एकटे नाही. 💙",
      },
      tabs: [
        { id: "wellness", emoji: "🌸", title: "आरोग्य", subtitle: "मानसिक आरोग्य मजबूत ठेवण्यासाठी सोप्या सवयी." },
        { id: "mindfulness", emoji: "🧠", title: "सजगता", subtitle: "दैनंदिन जीवनासाठी ध्यानाच्या पद्धती." },
        { id: "habits", emoji: "🔄", title: "सवयी", subtitle: "मानसिक आरोग्यात दिनचर्येचे महत्त्व." },
      ],
    },
    features: {
      title1: "तुमच्या",
      title2: "गरजेच्या सर्व गोष्टी",
      title3: "तुमच्या",
      title4: "आरोग्य प्रवासासाठी",
      cta: "आत्ताच मदत घ्या",
      services: [
        { badgeText: "24/7 मदत", title: "कॉल सेवा", description: "जेव्हा बोलायची गरज असेल तेव्हा सहानुभूतिपूर्ण मानवी-सहाय्यित कॉल मदत मिळवा.", ctaText: "कॉल सुरू करा" },
        { badgeText: "एआय सोबती", title: "वैयक्तिक चॅटबॉट", description: "तुमच्या भावनिक अवस्थेनुसार जुळणाऱ्या बुद्धिमान एआय सोबतीशी बोला.", ctaText: "आता चॅट करा" },
        { badgeText: "स्व-देखभाल", title: "मूड ट्रॅकिंग + स्क्रीनिंग", description: "दैनंदिन भावना नोंदवा आणि आरोग्याचा कल गोपनीयपणे तपासा.", ctaText: "मूड तपासा" },
        { badgeText: "तपासलेली काळजी", title: "तत्काळ संपर्क", description: "तुमच्या परिसरातील मानसिक आरोग्य तज्ज्ञ शोधा आणि संपर्क करा.", ctaText: "डॉक्टर शोधा" },
        { badgeText: "सर्वसमावेशक प्रवेश", title: "बहुभाषिक सहाय्य", description: "तुमच्या पसंतीच्या भाषेत सानुकूलित आरोग्य सामग्री आणि एआय संभाषण मिळवा.", ctaText: "भाषा बदला" },
      ],
    },
    blog: {
      title1: "अलीकडील",
      title2: "मानसिक आरोग्य",
      title3: "लेख आणि निरीक्षणे",
      intro: "आमच्या प्रमाणित तज्ज्ञांकडून व्यावहारिक वैद्यकीय मार्गदर्शन, आरोग्य धोरणे आणि वैज्ञानिक माहिती वाचा.",
      articles: [
        { headline: "दररोजच्या जीवनात सजगता जोपासणे", excerpt: "काही मिनिटांत उपस्थिती वाढवणे, ताण कमी करणे आणि भावनिक स्थिरता परत मिळवणे यासाठी सोप्या पद्धती जाणून घ्या.", tag: "सजगता", writer: "डॉ. अनन्या सेन" },
        { headline: "ताण समजून घेणे: करुणामय मार्गदर्शक", excerpt: "ताण हा अपयश नसून एक संकेत आहे. तुमचे ट्रिगर ओळखा आणि करुणेने प्रतिसाद द्या.", tag: "स्व-देखभाल", writer: "सिद्धार्थ मेहता" },
        { headline: "भावनिक स्क्रीनिंगचे महत्त्व", excerpt: "नियमित आत्ममूल्यांकन आणि भावनिक ट्रॅकिंग दीर्घकालीन मानसिक प्रतिकारशक्तीची पायाभरणी का आहेत.", tag: "मानसिक आरोग्य", writer: "डॉ. कबीर रॉय" },
      ],
    },
    footer: {
      title1: "पुन्हा विचार करा",
      title2: "फायदे",
      title3: "चे",
      title4: "ध्यान",
      intro: "ध्यानाचे फायदे विचारात घ्या. जर तुम्हाला नको असेल, तर आम्ही तुमच्यासाठी करू शकतो.",
      subscribe: "सदस्य व्हा",
      email: "तुमचा ईमेल टाका",
      supportTitle: "मदत",
      navTitle: "नेव्हिगेशन",
      supportLinks: ["मदत", "हेल्प सेंटर", "संपर्क करा", "FAQ"],
      navLinks: [
        { label: "मुखपृष्ठ", href: "/" },
        { label: "तज्ज्ञ", href: "#specialists" },
        { label: "ब्लॉग", href: "#blog" },
      ],
      socialLinks: ["इंस्टाग्राम", "ट्विटर", "लिंक्डइन"],
      legalLinks: ["गोपनीयता धोरण", "वापर अटी"],
      copyright: "© 2026 साथी. सर्व हक्क राखीव.",
      brand: "तुमच्या मातृभाषेत करुणामय एआय सहाय्य.",
    },
  },
  kn: {
    nav: {
      home: "ಮುಖಪುಟ",
      about: "ಪರಿಚಯ",
      features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
      blog: "ಬ್ಲಾಗ್",
      dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
      chat: "ಚಾಟ್",
      journal: "ಜರ್ನಲ್",
      assessments: "ಮೌಲ್ಯಮಾಪನಗಳು",
      appointments: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು",
      patients: "ರೋಗಿಗಳು",
      registerPatient: "ರೋಗಿಯನ್ನು ನೋಂದಾಯಿಸಿ",
      mobile: "ಮೊಬೈಲ್ ನ್ಯಾವಿಗೇಶನ್",
      sidebar: "ವಿಭಾಗ ನ್ಯಾವಿಗೇಶನ್",
      calmMode: "ಶಾಂತ, ಗೌಪ್ಯತೆ-ಮೊದಲ ಕಾರ್ಯಸ್ಥಳ",
      signIn: "ಸೈನ್ ಇನ್",
      getStarted: "ಪ್ರಾರಂಭಿಸಿ",
      profile: "ಪ್ರೊಫೈಲ್",
      wellness: "ನನ್ನ ಕ್ಷೇಮ",
      chatHistory: "ಚಾಟ್ ಇತಿಹಾಸ",
      settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
      signOut: "ಸೈನ್ ಔಟ್",
      language: "ಭಾಷೆ ಬದಲಿಸಿ",
      support: "ಸಹಾಯ",
      navigation: "ನ್ಯಾವಿಗೇಶನ್",
      social: "ಸಾಮಾಜಿಕ",
      legal: "ಕಾನೂನು",
    },
    hero: {
      badge: "ಎಐ-ಚಾಲಿತ ಕ್ಷೇಮ",
      title1: "ಕರුණಾಮಯ ಎಐ",
      title2: "ಬೆಂಬಲ",
      title3: "ನಿಮ್ಮ",
      title4: "ತವರಭಾಷೆಯಲ್ಲಿ.",
      subtitle:
        "ಗ್ರಾಮೀಣ ಮತ್ತು ಕಡಿಮೆ ಸೌಲಭ್ಯಗಳ ಸಮುದಾಯಗಳಿಗಾಗಿ ಬಹುಭಾಷಾ ಭಾವನಾತ್ಮಕ ಕ್ಷೇಮ ಸಹಾಯ - ಖಾಸಗಿ, ಸುರಕ್ಷಿತ ಮತ್ತು ಯಾವಾಗಲೂ ಲಭ್ಯ.",
      trust: ["ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್ಕ್ರಿಪ್ಟೆಡ್", "ಖಾತೆ ಅಗತ್ಯವಿಲ್ಲ", "ಕಡಿಮೆ ಬ್ಯಾಂಡ್‌ವಿಡ್ತ್‌ನಲ್ಲೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ"],
      start: "ನಿಮ್ಮ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ",
      learn: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
      availableIn: "ಲಭ್ಯವಿರುವ ಭಾಷೆಗಳು:",
      languages: ["English", "हिन्दी", "मराठी", "ಕನ್ನಡ", "தமிழ்"],
      live: "ಲೈವ್",
      voice: "ಧ್ವನಿ ಬೆಂಬಲ",
      voiceBody: "ಹಿಂದಿ, ಮರಾಠಿ, ಕನ್ನಡ, ತಮಿಳು ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಮಾತನಾಡಿ",
      private: "ಸಂಪೂರ್ಣ ಖಾಸಗಿ",
      privateBody: "ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್ಕ್ರಿಪ್ಟೆಡ್. ನಿಮ್ಮ ಸಂಭಾಷಣೆಗಳನ್ನು ಎಂದಿಗೂ ಹಂಚಿಕೊಳ್ಳುವುದಿಲ್ಲ.",
      whatsapp: "ವಾಟ್ಸಾಪ್ ಬೆಂಬಲ",
      whatsappBody: "ವಾಟ್ಸಾಪ್ ಮೂಲಕ ಚಾಟ್ ಮಾಡಿ - ಆಪ್ ಅಗತ್ಯವಿಲ್ಲ",
      stats: [
        { value: "5+", label: "ಭಾಷೆಗಳು" },
        { value: "10K+", label: "ಬೆಂಬಲಿತ ಬಳಕೆದಾರರು" },
        { value: "24/7", label: "ಲಭ್ಯತೆ" },
      ],
      sampleUser: "ನನಗೆ ಇಂದು ತುಂಬಾ ದಣಿವು ಆಗುತ್ತಿದೆ.",
      sampleReply: "ನನಗೆ ಅರ್ಥವಾಗಿದೆ. ಇನ್ನಷ್ಟು ಹೇಳುತ್ತೀರಾ?",
    },
    about: {
      lead: "ಮಾನಸಿಕ ಆರೋಗ್ಯ",
      title1: "ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವಿಕೆ,",
      title2: "ಕಾಳಜಿ ಮತ್ತು",
      title3: "ನಿಮ್ಮ ಆದ್ಯತೆ.",
      body1: "ನೀವು ನಿಮ್ಮ ದೇಹದ ಕಾಳಜಿ ತೆಗೆದುಕೊಳ್ಳುವಂತೆ, ನಿಮ್ಮ ಮನಸ್ಸಿಗೂ ಸಂಪೂರ್ಣ ಕಾಳಜಿ ಮತ್ತು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವಿಕೆ ಅಗತ್ಯ.",
      body2:
        "ಸಾಥಿ ಗ್ರಾಮೀಣ ಸಮುದಾಯಗಳು ಮತ್ತು ವೃತ್ತಿಪರ ಮಾನಸಿಕ ಕ್ಷೇಮ ಬೆಂಬಲದ ನಡುವಿನ ಅಂತರವನ್ನು ತುಂಬುತ್ತದೆ - ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ, ಯಾವುದೇ ಸಮಯದಲ್ಲಿ, ಸಂಪೂರ್ಣ ಖಾಸಗಿಯಾಗಿ.",
    },
    mood: {
      title1: "ನೀವು",
      title2: "ಹೇಗೆ",
      title3: "ಭಾವಿಸುತ್ತ",
      title4: "ಇದ್ದೀರಾ ಇಂದು?",
      moods: {
        happy: "ಅದ್ಭುತ! ನಿಮ್ಮ ಸಂತೋಷ ಎಲ್ಲರಿಗೂ ಬೆಳಕು ನೀಡುತ್ತದೆ. ✨",
        angry: "ಇದರಿಂದ ಹೀಗೇ ಅನಿಸುವುದು ಸರಿ. ಒಟ್ಟಿಗೆ ಉಸಿರೆಳೆಯೋಣ.",
        good: "ಅದು ಕೇಳಿ ಚೆನ್ನಾಗಿದೆ! ಆ ಧನಾತ್ಮಕ ಶಕ್ತಿಯನ್ನು ಉಳಿಸಿಕೊಳ್ಳಿ.",
        calm: "ಶಾಂತ ಮನಸ್ಸೇ ನಿಮ್ಮ ದೊಡ್ಡ ಶಕ್ತಿ. 🌊",
        sad: "ನಾವು ನಿಮ್ಮ ಜೊತೆ ಇದ್ದೇವೆ. ನೀವು ಒಬ್ಬರಲ್ಲ. 💙",
      },
      tabs: [
        { id: "wellness", emoji: "🌸", title: "ಕ್ಷೇಮ", subtitle: "ಮಾನಸಿಕ ಆರೋಗ್ಯವನ್ನು ಬಲಪಡಿಸುವ ಸರಳ ಅಭ್ಯಾಸಗಳು." },
        { id: "mindfulness", emoji: "🧠", title: "ಸಜಾಗತೆ", subtitle: "ದೈನಂದಿನ ಜೀವನಕ್ಕಾಗಿ ಧ್ಯಾನ ಅಭ್ಯಾಸಗಳು." },
        { id: "habits", emoji: "🔄", title: "ಅಭ್ಯಾಸಗಳು", subtitle: "ಮಾನಸಿಕ ಆರೋಗ್ಯದಲ್ಲಿ ರೂಟೀನ್‌ನ ಶಕ್ತಿ." },
      ],
    },
    features: {
      title1: "ನಿಮಗೆ ಬೇಕಾದ",
      title2: "ಎಲ್ಲವೂ",
      title3: "ನಿಮ್ಮ",
      title4: "ಕ್ಷೇಮ ಪ್ರಯಾಣಕ್ಕೆ",
      cta: "ಈಗ ಸಹಾಯ ಪಡೆಯಿರಿ",
      services: [
        { badgeText: "24/7 ಬೆಂಬಲ", title: "ಕಾಲ್ ಸೇವೆಗಳು", description: "ನೀವು ಮಾತನಾಡಬೇಕಾದಾಗಲೆಲ್ಲಾ ಸಹಾನುಭೂತಿಯ ಮಾನವ ಬೆಂಬಲಿತ ಕರೆಗಳನ್ನು ತಕ್ಷಣ ಪಡೆಯಿರಿ.", ctaText: "ಕಾಲ್ ಪ್ರಾರಂಭಿಸಿ" },
        { badgeText: "ಎಐ ಜೊತೆಯಾಳು", title: "ವೈಯಕ್ತಿಕ ಚಾಟ್‌ಬಾಟ್", description: "ನಿಮ್ಮ ಭಾವನಾತ್ಮಕ ಸ್ಥಿತಿಗೆ ತಕ್ಕಂತೆ ಹೊಂದಿಕೊಳ್ಳುವ ಬುದ್ಧಿವಂತ ಎಐ ಜೊತೆಯಾಳಿನೊಂದಿಗೆ ಮಾತನಾಡಿ.", ctaText: "ಈಗ ಚಾಟ್ ಮಾಡಿ" },
        { badgeText: "ಸ್ವ-ಪರಿಚರಣೆ", title: "ಮೂಡ್ ಟ್ರ್ಯಾಕಿಂಗ್ + ಸ್ಕ್ರೀನಿಂಗ್", description: "ನಿಮ್ಮ ದೈನಂದಿನ ಭಾವನೆಗಳನ್ನು ಗಮನಿಸಿ ಮತ್ತು ಕ್ಷೇಮದ ಪ್ರವೃತ್ತಿಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.", ctaText: "ಮೂಡ್ ಪರಿಶೀಲಿಸಿ" },
        { badgeText: "ಪರಿಶೀಲಿತ ಆರೈಕೆ", title: "ತಕ್ಷಣದ ಸಂಪರ್ಕ", description: "ನಿಮ್ಮ ಪ್ರದೇಶದ ಮಾನಸಿಕ ಆರೋಗ್ಯ ತಜ್ಞರನ್ನು ಹುಡುಕಿ ಮತ್ತು ಸಂಪರ್ಕಿಸಿ.", ctaText: "ಡಾಕ್ಟರ್ ಹುಡುಕಿ" },
        { badgeText: "ಸಾರ್ವತ್ರಿಕ ಪ್ರವೇಶ", title: "ಬಹುಭಾಷಾ ಬೆಂಬಲ", description: "ನಿಮ್ಮ ಇಷ್ಟದ ಭಾಷೆಯಲ್ಲಿ ಹೊಂದಿಕೊಂಡ ಕ್ಷೇಮ ವಿಷಯ ಮತ್ತು ಎಐ ಸಂಭಾಷಣೆ ಪಡೆಯಿರಿ.", ctaText: "ಭಾಷೆ ಬದಲಿಸಿ" },
      ],
    },
    blog: {
      title1: "ಇತ್ತೀಚಿನ",
      title2: "ಮಾನಸಿಕ ಆರೋಗ್ಯ",
      title3: "ಲೇಖನಗಳು ಮತ್ತು ಒಳನೋಟಗಳು",
      intro: "ನಮ್ಮ ಪ್ರಮಾಣಿತ ತಜ್ಞರಿಂದ ಪ್ರಾಯೋಗಿಕ ವೈದ್ಯಕೀಯ ಮಾರ್ಗದರ್ಶನ, ಕ್ಷೇಮ ತಂತ್ರಗಳು ಮತ್ತು ವೈಜ್ಞಾನಿಕ ಮಾಹಿತಿಯನ್ನು ಅನ್ವೇಷಿಸಿ.",
      articles: [
        { headline: "ದೈನಂದಿನ ಜೀವನದಲ್ಲಿ ಸಜಾಗತೆಯನ್ನು ಪೋಷಿಸುವುದು", excerpt: "ಕೆಲವೇ ನಿಮಿಷಗಳಲ್ಲಿ ಉಪಸ್ಥಿತಿಯನ್ನು ಹೆಚ್ಚಿಸಲು, ಒತ್ತಡವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಮತ್ತು ಭಾವನಾತ್ಮಕ ಸ್ಥಿರತೆಯನ್ನು ಮರಳಿ ಪಡೆಯಲು ಸರಳ ವಿಧಾನಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", tag: "ಸಜಾಗತೆ", writer: "ಡಾ. ಅನನ್ಯ ಸೇನ್" },
        { headline: "ಒತ್ತಡವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು: ಸಹಾನುಭೂತಿಯ ಮಾರ್ಗದರ್ಶಿ", excerpt: "ಒತ್ತಡವು ವಿಫಲತೆ ಅಲ್ಲ, ಒಂದು ಸೂಚನೆ. ನಿಮ್ಮ ಟ್ರಿಗರ್‌ಗಳನ್ನು ಗುರುತಿಸಿ ಮತ್ತು ಸಹಾನುಭೂತಿಯಾಗಿ ಪ್ರತಿಕ್ರಿಯಿಸಿ.", tag: "ಸ್ವ-ಪರಿಚರಣೆ", writer: "ಸಿದ್ಧಾರ್ಥ ಮೆಹ್ತಾ" },
        { headline: "ಭಾವನಾತ್ಮಕ ಸ್ಕ್ರೀನಿಂಗ್‌ನ ಮಹತ್ವ", excerpt: "ನಿಯಮಿತ ಸ್ವ-ಮೌಲ್ಯಮಾಪನ ಮತ್ತು ಭಾವನಾತ್ಮಕ ಟ್ರ್ಯಾಕಿಂಗ್ ದೀರ್ಘಕಾಲೀನ ಮಾನಸಿಕ ದೃಢತೆಗೆ ಏಕೆ ಪ್ರಮುಖವಾಗಿವೆ.", tag: "ಮಾನಸಿಕ ಆರೋಗ್ಯ", writer: "ಡಾ. ಕಬೀರ್ ರಾಯ್" },
      ],
    },
    footer: {
      title1: "ಮರುಚಿಂತನೆ ಮಾಡಿ",
      title2: "ಲಾಭಗಳು",
      title3: "ಆಫ್",
      title4: "ಧ್ಯಾನ",
      intro: "ಧ್ಯಾನದ ಲಾಭಗಳ ಬಗ್ಗೆ ಯೋಚಿಸಿ. ನೀವು ಬಯಸದಿದ್ದರೆ, ನಾವು ಅದನ್ನು ನಿಮ್ಮಗಾಗಿ ಮಾಡಬಹುದು.",
      subscribe: "ಚಂದಾದಾರರಾಗಿ",
      email: "ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ",
      supportTitle: "ಸಹಾಯ",
      navTitle: "ನ್ಯಾವಿಗೇಶನ್",
      supportLinks: ["ಸಹಾಯ", "ಸಹಾಯ ಕೇಂದ್ರ", "ಸಂಪರ್ಕಿಸಿ", "FAQ"],
      navLinks: [
        { label: "ಮುಖಪುಟ", href: "/" },
        { label: "ತಜ್ಞರು", href: "#specialists" },
        { label: "ಬ್ಲಾಗ್", href: "#blog" },
      ],
      socialLinks: ["ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್", "ಟ್ವಿಟರ್", "ಲಿಂಕ್ಡ್ಇನ್"],
      legalLinks: ["ಗೌಪ್ಯತಾ ನೀತಿ", "ಬಳಕೆಯ ನಿಯಮಗಳು"],
      copyright: "© 2026 ಸಾಥಿ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
      brand: "ನಿಮ್ಮ ತವರಭಾಷೆಯಲ್ಲಿ ಸಹಾನುಭೂತಿಯ ಎಐ ಬೆಂಬಲ.",
    },
  },
  ta: {
    nav: {
      home: "முகப்பு",
      about: "அறிமுகம்",
      features: "அம்சங்கள்",
      blog: "பதிவு",
      dashboard: "டாஷ்போர்டு",
      chat: "அரட்டை",
      journal: "ஜர்னல்",
      assessments: "மதிப்பீடுகள்",
      appointments: "முன்பதிவுகள்",
      patients: "நோயாளிகள்",
      registerPatient: "நோயாளியை பதிவு செய்யவும்",
      mobile: "மொபைல் வழிசெலுத்தல்",
      sidebar: "பிரிவு வழிசெலுத்தல்",
      calmMode: "அமைதியான, தனியுரிமை முதன்மை பணிமனை",
      signIn: "உள்நுழை",
      getStarted: "தொடங்குங்கள்",
      profile: "சுயவிவரம்",
      wellness: "என் நலம்",
      chatHistory: "அரட்டை வரலாறு",
      settings: "அமைப்புகள்",
      signOut: "வெளியேறு",
      language: "மொழியை மாற்று",
      support: "ஆதரவு",
      navigation: "வழிசெலுத்தல்",
      social: "சமூக",
      legal: "சட்டம்",
    },
    hero: {
      badge: "AI இயக்கிய நலம்",
      title1: "கருணையுள்ள AI",
      title2: "ஆதரவு",
      title3: "உங்கள்",
      title4: "தாய்மொழியில்.",
      subtitle:
        "கிராமப்புற மற்றும் குறைந்த வசதியுள்ள சமூகங்களுக்கான பல்மொழி உணர்ச்சி நல உதவி - தனிப்பட்டது, பாதுகாப்பானது, எப்போதும் கிடைக்கும்.",
      trust: ["முழுமையான குறியாக்கம்", "கணக்கு தேவையில்லை", "குறைந்த பாண்ட்வித்-இலும் இயங்கும்"],
      start: "உங்கள் பயணத்தைத் தொடங்குங்கள்",
      learn: "மேலும் அறிக",
      availableIn: "கிடைக்கும் மொழிகள்:",
      languages: ["English", "हिन्दी", "मराठी", "ಕನ್ನಡ", "தமிழ்"],
      live: "நேரலை",
      voice: "குரல் ஆதரவு",
      voiceBody: "இந்தி, மராத்தி, கன்னடம், தமிழில் அல்லது ஆங்கிலத்தில் பேசுங்கள்",
      private: "முழுமையாக தனிப்பட்டது",
      privateBody: "முழுமையான குறியாக்கம். உங்கள் உரையாடல்கள் ஒருபோதும் பகிரப்படாது.",
      whatsapp: "வாட்ஸ்அப் ஆதரவு",
      whatsappBody: "வாட்ஸ்அப்பில் அரட்டை - பயன்பாடு தேவையில்லை",
      stats: [
        { value: "5+", label: "மொழிகள்" },
        { value: "10K+", label: "பயனர்கள் ஆதரவு" },
        { value: "24/7", label: "கிடைக்கும் நேரம்" },
      ],
      sampleUser: "இன்று நான் மிகவும் சோர்வாக உணர்கிறேன்.",
      sampleReply: "நான் புரிந்துகொள்கிறேன். மேலும் சொல்ல விரும்புகிறீர்களா?",
    },
    about: {
      lead: "மனநலம்",
      title1: "புரிதல்,",
      title2: "கவனிப்பு மற்றும்",
      title3: "உங்கள் முன்னுரிமை.",
      body1: "உங்கள் உடலைப் போலவே, உங்கள் மனமும் முழுமையான கவனமும் புரிதலும் பெறத் தகுந்தது.",
      body2:
        "சாதி கிராமப்புற சமூகங்களுக்கும் தொழில்முறை மனநல ஆதரவுக்கும் இடையேயான இடைவெளியை நிரப்புகிறது - உங்கள் மொழியில், எந்த நேரத்திலும், முழுமையாக தனிப்பட்டது.",
    },
    mood: {
      title1: "நீங்கள்",
      title2: "எப்படி",
      title3: "உணர்கிறீர்கள்",
      title4: "இன்று?",
      moods: {
        happy: "அற்புதம்! உங்கள் மகிழ்ச்சி அறையை ஒளிரச் செய்கிறது. ✨",
        angry: "இப்படிப் பொருந்துவது சரி. ஒன்றாக மூச்சை இழுப்போம்.",
        good: "நன்றாக இருக்கிறது! அந்த நேர்மறை ஆற்றலை தொடர்ந்து பேணுங்கள்.",
        calm: "அமைதியான மனம் உங்கள் மிகப்பெரிய பலம். 🌊",
        sad: "நாங்கள் உங்களுடன் இருக்கிறோம். நீங்கள் ஒருபோதும் தனியாக இல்லை. 💙",
      },
      tabs: [
        { id: "wellness", emoji: "🌸", title: "நலம்", subtitle: "மனநலத்தை வலுப்படுத்தும் எளிய பழக்கங்கள்." },
        { id: "mindfulness", emoji: "🧠", title: "கவனயிடம்", subtitle: "தினசரி வாழ்க்கைக்கான தியானப் பயிற்சிகள்." },
        { id: "habits", emoji: "🔄", title: "பழக்கங்கள்", subtitle: "மனநலத்தில் வழக்கத்தின் சக்தி." },
      ],
    },
    features: {
      title1: "உங்களுக்குத் தேவைப்படும்",
      title2: "அனைத்தும்",
      title3: "உங்கள்",
      title4: "நலப் பயணத்திற்காக",
      cta: "இப்போது உதவி பெறுங்கள்",
      services: [
        { badgeText: "24/7 ஆதரவு", title: "அழைப்பு சேவைகள்", description: "நீங்கள் பேச வேண்டிய எந்த நேரத்திலும் கருணையுள்ள மனித உதவி-கலந்த அழைப்புகளை உடனே பெறுங்கள்.", ctaText: "அழைப்பைத் தொடங்கு" },
        { badgeText: "AI துணைவர்", title: "தனிப்பயன் சாட்பாட்", description: "உங்கள் உணர்ச்சி நிலைக்கு ஏற்ப தன்னை மாற்றிக்கொள்ளும் புத்திசாலி AI துணைவருடன் உரையாடுங்கள்.", ctaText: "இப்போது அரட்டை" },
        { badgeText: "சுய பராமரிப்பு", title: "மனம் கண்காணிப்பு + பரிசோதனை", description: "உங்கள் தினசரி உணர்வுகளை கண்காணித்து, நலப் போக்குகளை பாதுகாப்பாகவும் தனிப்பட்ட முறையிலும் அறியுங்கள்.", ctaText: "மனநிலை பார்க்க" },
        { badgeText: "உறுதி செய்யப்பட்ட பராமரிப்பு", title: "உடனடி தொடர்பு", description: "உங்கள் அருகிலுள்ள மனநல நிபுணர்களைக் கண்டுபிடித்து இணைக.", ctaText: "மருத்துவர் தேடு" },
        { badgeText: "எல்லோருக்கும் அணுகல்", title: "பல்மொழி ஆதரவு", description: "உங்கள் விருப்பமான மொழியில் தனிப்பயன் நலப் பொருட்களையும் AI உரையாடலையும் பெறுங்கள்.", ctaText: "மொழி மாற்று" },
      ],
    },
    blog: {
      title1: "சமீபத்திய",
      title2: "மனநலம்",
      title3: "கட்டுரைகள் & பார்வைகள்",
      intro: "எங்கள் உறுதி செய்யப்பட்ட நிபுணர்களிடமிருந்து நடைமுறை மருத்துவ வழிகாட்டல், நலத்திட்டங்கள் மற்றும் அறிவியல் தகவல்களை ஆராயுங்கள்.",
      articles: [
        { headline: "தினசரி வாழ்வில் கவனயிடத்தை வளர்த்தல்", excerpt: "சில நிமிடங்களில் ஆழமான இருப்பை வளர்த்தல், தினசரி மன அழுத்தத்தை குறைத்தல், மற்றும் உணர்ச்சி நிலைத்தன்மையை மீட்டெடுப்பதற்கான எளிய முறைகள்.", tag: "கவனயிடம்", writer: "டாக்டர் அனன்யா சென்" },
        { headline: "மன அழுத்தத்தைப் புரிந்துகொள்வது: கருணைமிக்க வழிகாட்டி", excerpt: "மன அழுத்தம் ஒரு தோல்வி அல்ல, ஒரு அறிகுறி. உங்கள் உடல் தூண்டுதல்களை வரைபடம் செய்து, கருணையுடன் பதிலளிப்பது எப்படி என்று கற்றுக்கொள்ளுங்கள்.", tag: "சுய பராமரிப்பு", writer: "சித்தார்த் மேத்தா" },
        { headline: "உணர்ச்சி பரிசோதனையின் முக்கியத்துவம்", excerpt: "தொடர்ச்சியான தன்னிலை மதிப்பீடுகள் மற்றும் உணர்ச்சி கண்காணிப்பு நீண்டகால மன உறுதியின் அடித்தளமாக இருப்பதன் காரணம்.", tag: "மனநலம்", writer: "டாக்டர் கபீர் ராய்" },
      ],
    },
    footer: {
      title1: "மறுபரிசீலனை செய்யுங்கள்",
      title2: "பலன்கள்",
      title3: "இன்",
      title4: "தியானம்",
      intro: "தியானத்தின் பலன்களைப் பற்றி சிந்தியுங்கள். விரும்பவில்லை என்றால், அதை நாங்கள் உங்களுக்காக செய்து விடலாம்.",
      subscribe: "சந்தா சேருங்கள்",
      email: "உங்கள் மின்னஞ்சலை உள்ளிடுங்கள்",
      supportTitle: "ஆதரவு",
      navTitle: "வழிசெலுத்தல்",
      supportLinks: ["ஆதரவு", "உதவி மையம்", "தொடர்பு கொள்ளுங்கள்", "FAQ"],
      navLinks: [
        { label: "முகப்பு", href: "/" },
        { label: "நிபுணர்கள்", href: "#specialists" },
        { label: "பதிவு", href: "#blog" },
      ],
      socialLinks: ["இன்ஸ்டாகிராம்", "ட்விட்டர்", "லிங்க்ட்இன்"],
      legalLinks: ["தனியுரிமைக் கொள்கை", "பயன்பாட்டு விதிமுறைகள்"],
      copyright: "© 2026 சாதி. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
      brand: "உங்கள் தாய்மொழியில் கருணையுள்ள AI ஆதரவு.",
    },
  },
};

// Telugu translations (machine-translated first-pass). Replace or refine as needed.
(siteCopy as any).te = {
  nav: {
    home: "హోమ్",
    about: "పరిచయం",
    features: "వైశిష్ట్యాలు",
    blog: "బ్లాగ్",
    dashboard: "డ్యాష్‌బోర్డు",
    chat: "చాట్",
    journal: "జర్నల్",
    assessments: "మూల్యాంకనాలు",
    appointments: "అపాయింట్‌మెంట్‌లు",
    patients: "రోగులు",
    registerPatient: "రోగిని నమోదు చేయండి",
    mobile: "మొబైల్ నావిగేషన్",
    sidebar: "విభాగ్ నావిగేషన్",
    calmMode: "శాంతి, గోప్యత్వముభరిత పని ప్రాంతం",
    signIn: "సైన్ ఇన్",
    getStarted: "ప్రారంభించండి",
    profile: "ప్రొఫైల్",
    wellness: "నా వెల్నెస్",
    chatHistory: "చాట్ చరిత్ర",
    settings: "సెట్టింగ్లు",
    signOut: "లాగ్ అవుట్",
    language: "భాష మార్చండి",
    support: "సహాయం",
    navigation: "నావిగేషన్",
    social: "సోషల్",
    legal: "చట్టపరమైన",
  },
  hero: {
    badge: "AI-చాలిత వెల్నెస్",
    title1: "సహానుభూతితో కూడిన AI",
    title2: "సహాయం",
    title3: "మీ",
    title4: "స్థానిక భాషలో.",
    subtitle:
      "గ్రామీణ మరియు సేవలు తక్కువగా ఉన్న ప్రాంతాల కోసం బహుభాషా భావోద్వేగ ఆరోగ్య సహాయం — ప్రైవేట్, సురక్షితం, ఎప్పుడూ అందుబాటులో.",
    trust: ["ఎండ్-టు-ఎండ్ సంకేతీకరణ", "ఖాతా అవసరం లేదు", "తక్కువ బ్యాండ్‌విడ్థ్‌లో పనిచేస్తుంది"],
    start: "మీ ప్రయాణాన్ని ప్రారంభించండి",
    learn: "మరింత తెలుసుకోండి",
    availableIn: "లభ్య భాషలు:",
    languages: ["English", "हिन्दी", "मराठी", "ಕನ್ನಡ", "தமிழ்"],
    live: "నేరుగా",
    voice: "వాయిస్ సహాయం",
    voiceBody: "హిందీ, మరాఠీ, కన్నడ, తమిళ్ లేదా ఇంగ్లీష్‌లో మాట్లాడండి",
    private: "పూర్తిగా ప్రైవేట్",
    privateBody: "ఎండ్-టు-ఎండ్ సంకేతీకరణ. మీ సంభాషణలు ఎప్పుడూ భాగస్వామ్యం చేయబడవు.",
    whatsapp: "వాట్సాప్ సహాయం",
    whatsappBody: "వాట్సాప్ ద్వారా చాట్ చేయండి - యాప్ అవసరం లేదు",
    stats: [
      { value: "5+", label: "భాషలు" },
      { value: "10K+", label: "వినియోగదారులు" },
      { value: "24/7", label: "అందుబాటు" },
    ],
    sampleUser: "నేడు నాకు చాలా అలసిపోయినట్టుగా ఉంది.",
    sampleReply: "నాకు అర్ధమైంది. మీరు ఇంకా చెప్పాలనుకుంటున్నారా?",
  },
  about: {
    lead: "మానసిక ఆరోగ్యం",
    title1: "అర్థం,",
    title2: "ప్యారూ మరియు",
    title3: "మీ ప్రాధాన్యత.",
    body1: "మీ శరీరానికి మీరు చూసుకొనినట్లే, మీ మనస్సుకూ కూడా పూర్తి శ్రద్ధ మరియు అర్థం అవసరం.",
    body2:
      "సాథీ గ్రామీణ సముదాయాలనుంచి వృత్తిపరమైన మానసిక ఆరోగ్య మద్దతు వరకూ గల ఖాళీలను నిర్మూలిస్తుంది — మీ భాషలో, ఎప్పుడైనా, పూర్తిగా గోప్యంగా.",
  },
  mood: {
    title1: "మీరు ఎలా",
    title2: "అనుభూతి",
    title3: "కూర్చున్నారా",
    title4: "ఈరోజు?",
    moods: {
      happy: "అది అద్భుతం! మీ ఆనందం చుట్టూ ఉన్నవారిని ఆనందపరుస్తుంది. ✨",
      angry: "ఈ భావాన్ని అనుభవించడం సరే. మనం కలిసి శ్వాస తీసుకుందాం.",
      good: "బాగా ఉంది! ఆ సానుకూల శక్తిని పెంపొందించండి.",
      calm: "శాంతిమయమైన మనసు మీ గొప్ప బలం. 🌊",
      sad: "మేము మీతో ఉన్నాం. మీరు ఒంటరి కావడం లేదు. 💙",
    },
    tabs: [
      { id: "wellness", emoji: "🌸", title: "వెల్నెస్", subtitle: "మీ మానసిక ఆరోగ్యం బలోపేతం చేసే సరళమైన అలవాట్లు." },
      { id: "mindfulness", emoji: "🧠", title: "మైండ్‌ఫుల్నెస్", subtitle: "ప్రతిరోజూ జీవితానికి ధ్యానం అభ్యాసాలు." },
      { id: "habits", emoji: "🔄", title: "ఆదతలు", subtitle: "మానసిక ఆరోగ్యంలో రొటీన్ శక్తి." },
    ],
  },
  features: {
    title1: "మీకు అవసరమైన",
    title2: "అన్నీ",
    title3: "మీ",
    title4: "వెల్నెస్ ప్రయాణానికి",
    cta: "ఇప్పుడు సహాయం పొందండి",
    services: [
      { badgeText: "24/7 సహాయం", title: "కాల్ సేవలు", description: "మీరు మాట్లాడాలనుకుంటే ఎలాంటి సమయంలోనైనా మనుష్య సహాయం కలిగించే కాల్స్.", ctaText: "కాల్ ప్రారంభించండి" },
      { badgeText: "AI తోటి", title: "వ్యక్తిగత చాట్‌బాట్", description: "మీ భావోద్వేగ స్థితికి అనుగుణంగా మారే తెలివైన AI తో మాట్లాడండి.", ctaText: "ఇప్పుడు చాట్ చేయండి" },
      { badgeText: "స్వీయ సంరక్షణ", title: "మూడ్ ట్రాకింగ్ + స్క్రీనింగ్", description: "మీ రోజువారీ భావోద్వేగాలను గమనించండి మరియు రహస్యంగా స్క్రీన్ చేయండి.", ctaText: "మూడ్ తనిఖీ చేయండి" },
      { badgeText: "ఆధారిత సంరక్షణ", title: "క్షణిక కమ్యూనికేషన్", description: "మీ పరిధిలో ఉన్న వృత్తిపరులైన మానసిక ఆరోగ్య నిపుణులను కనుగొని అవార్డులు పొందండి.", ctaText: "డాక్టర్ని కనుగొనండి" },
      { badgeText: "ప్రత్యేక అనుకూలత", title: "బహుభాషా సహాయం", description: "మీ ఇష్ట భాషలో వ్యక్తిగతమైన వెల్నెస్ వస్తువులు మరియు AI సంభాషణలు అందుకోండి.", ctaText: "భాష మార్చండి" },
    ],
  },
  blog: {
    title1: "తాజా",
    title2: "మానసిక ఆరోగ్య",
    title3: "వ్యాసాలు & అవగాహనలు",
    intro: "మా ధృవీకరించిన నిపుణులు అందించే ఆచరణాత్మక మార్గదర్శకాలు, వెల్నెస్ వ్యూహాలు మరియు శాస్త్రీయ అంశాలను అన్వేషించండి.",
    articles: [
      { headline: "దైనందిన జీవితంలో మైండ్‌ఫుల్నెస్‌ను పెంపొందించడం", excerpt: "లోతైన అవగాహనను పెంచేందుకు, రోజువారీ ఒత్తిడిని తగ్గించేందుకు మరియు భావోద్వేగ స్థిరత్వాన్ని తిరిగి పొందేందుకు సరళమైన, ఆచరణాత్మక పద్ధతులను తెలుసుకోండి.", tag: "మైండ్‌ఫుల్నెస్", writer: "డా. అనన్య సేన్" },
      { headline: "ఒత్తిడిని అర్థం చేసుకోవడం: సహానుభూతితో కూడిన మార్గదర్శి", excerpt: "ఒత్తిడి ఒక సహజ సంకేతం, వైఫల్యం కాదు. మీ శరీరంలోని ఒత్తిడి ప్రేరకాలను గుర్తించి, దానికి దయతో మరియు ఆరోగ్యకరమైన అలవాట్లతో ఎలా స్పందించాలో తెలుసుకోండి.", tag: "స్వీయ సంరక్షణ", writer: "సిద్ధార్థ్ మెహతా" },
      { headline: "భావోద్వేగ స్క్రీనింగ్ యొక్క ప్రాముఖ్యత", excerpt: "నిరంతర స్వీయ-మూల్యాంకనాలు మరియు భావోద్వేగ ట్రాకింగ్ దీర్ఘకాలిక మానసిక స్థైర్యానికి ఎలా ఆధారస్తంభాలవుతాయో తెలుసుకోండి.", tag: "మానసిక ఆరోగ్యం", writer: "డా. కబీర్ రాయ్" },
    ],
  },
  footer: {
    title1: "మీ ఆలోచనను మార్చుకోండి",
    title2: "మీ",
    title3: "మానసిక",
    title4: "ఆరోగ్యం",
    intro: "",
    subscribe: "సబ్‌స్క్రైబ్",
    email: "మీ ఇమెయిల్ నమోదు చేయండి",
    supportTitle: "సహాయం",
    navTitle: "నావిగేషన్",
    supportLinks: ["సహాయం", "హెల్ప్ సెంటర్", "సంప్రదించండి", "FAQ"],
    navLinks: [
      { label: "హోమ్", href: "/" },
      { label: "నిపుణులు", href: "#specialists" },
      { label: "బ్లాగ్", href: "#blog" },
    ],
    socialLinks: ["Instagram", "Twitter", "LinkedIn"],
    legalLinks: ["గోప్యతా విధానం", "వినియోగ నిబంధనలు"],
    copyright: "© 2026 Saathi. అన్ని హక్కులు సురక్షితం.",
    brand: "మీ స్థానిక భాషలో సహానుభూతి కలిగిన AI సహాయం.",
  },
};
