name: Backend CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend-core/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Docker Image
        run: |
          docker build -t jalrakshak-backend ./backend-core
          # push to registry
