name: Frontend CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend-ui/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          cd frontend-ui
          npm install
          npm run build
