class AppLocales {
  static final Map<String, Map<String, String>> _translations = {
    'English': {
      'welcome': 'Welcome back',
      'dashboard': 'Dashboard',
      'verify_skills': 'Ready to verify your skills today?',
      'start_assessment': 'Start Video Assessment',
      'record_work': 'Record your work to get certified instantly by AI',
      'top_skills': 'My Top Skills',
      'view_passport': 'View Passport',
      'profile': 'Profile',
      'logout': 'Log Out',
      'community': 'Community Verification',
      'state': 'State',
      'language': 'Language',
      'occupation': 'Occupation',
      'change_language': 'Change Language',
      'cancel': 'Cancel',
      'verify_peers': 'Verify Peers',
      'leaderboard': 'Leaderboard',
      'watch': 'Watch',
      'verify': 'Verify',
      'verifications_done': 'verifications done',
    },
    'Hindi': {
      'welcome': 'वापसी पर स्वागत है',
      'dashboard': 'डैशबोर्ड',
      'verify_skills': 'क्या आप आज अपने कौशल को सत्यापित करने के लिए तैयार हैं?',
      'start_assessment': 'वीडियो मूल्यांकन शुरू करें',
      'record_work': 'AI द्वारा तुरंत प्रमाणित होने के लिए अपना काम रिकॉर्ड करें',
      'top_skills': 'मेरे शीर्ष कौशल',
      'view_passport': 'पासपोर्ट देखें',
      'profile': 'प्रोफ़ाइल',
      'logout': 'लॉग आउट',
      'community': 'सामुदायिक सत्यापन',
      'state': 'राज्य',
      'language': 'भाषा',
      'occupation': 'पेशा',
      'change_language': 'भाषा बदलें',
      'cancel': 'रद्द करें',
      'verify_peers': 'साथियों को सत्यापित करें',
      'leaderboard': 'लीडरबोर्ड',
      'watch': 'देखें',
      'verify': 'सत्यापित करें',
      'verifications_done': 'सत्यापन हो गए',
    },
    'Tamil': {
      'welcome': 'மீண்டும் வருக',
      'dashboard': 'முகப்பு',
      'verify_skills': 'இன்று உங்கள் திறன்களை சரிபார்க்க தயாராக உள்ளீர்களா?',
      'start_assessment': 'வீடியோ மதிப்பீட்டைத் தொடங்கவும்',
      'record_work': 'AI மூலம் உடனடியாக சான்றிதழ் பெற உங்கள் வேலையை பதிவு செய்யவும்',
      'top_skills': 'எனது சிறந்த திறன்கள்',
      'view_passport': 'கடவுச்சீட்டைப் பார்க்கவும்',
      'profile': 'சுயவிவரம்',
      'logout': 'வெளியேறு',
      'community': 'சமூக சரிபார்ப்பு',
      'state': 'மாநிலம்',
      'language': 'மொழி',
      'occupation': 'தொழில்',
      'change_language': 'மொழியை மாற்றவும்',
      'cancel': 'ரத்து செய்',
      'verify_peers': 'சக நண்பர்களைச் சரிபார்க்கவும்',
      'leaderboard': 'லீடர்போர்டு',
      'watch': 'பார்க்க',
      'verify': 'சரிபார்க்க',
      'verifications_done': 'சரிபார்ப்புகள் முடிந்துள்ளன',
    },
    'Telugu': {
      'welcome': 'మళ్లీ స్వాగతం',
      'dashboard': 'డాష్‌బోర్డ్',
      'verify_skills': 'ఈరోజు మీ నైపుణ్యాలను ధృవీకరించడానికి సిద్ధంగా ఉన్నారా?',
      'start_assessment': 'వీడియో అంచనాను ప్రారంభించండి',
      'record_work': 'AI ద్వారా తక్షణమే ధృవీకరించబడటానికి మీ పనిని రికార్డ్ చేయండి',
      'top_skills': 'నా అగ్ర నైపుణ్యాలు',
      'view_passport': 'పాస్‌పోర్ట్ చూడండి',
      'profile': 'ప్రొఫైల్',
      'logout': 'లాగ్ అవుట్',
      'community': 'సంఘం ధృవీకరణ',
      'state': 'రాష్ట్రం',
      'language': 'భాష',
      'occupation': 'వృత్తి',
      'change_language': 'భాషను మార్చండి',
      'cancel': 'రద్దు చేయండి',
      'verify_peers': 'తోటివారిని ధృవీకరించండి',
      'leaderboard': 'లీడర్‌బోర్డ్',
      'watch': 'చూడండి',
      'verify': 'ధృవీకరించండి',
      'verifications_done': 'ధృవీకరణలు పూర్తయ్యాయి',
    },
    'Kannada': {
      'welcome': 'ಮರಳಿ ಸ್ವಾಗತ',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'verify_skills': 'ಇಂದು ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
      'start_assessment': 'ವೀಡಿಯೊ ಮೌಲ್ಯಮಾಪನ ಪ್ರಾರಂಭಿಸಿ',
      'record_work': 'AI ನಿಂದ ತಕ್ಷಣ ಪ್ರಮಾಣೀಕರಿಸಲು ನಿಮ್ಮ ಕೆಲಸವನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ',
      'top_skills': 'ನನ್ನ ಉನ್ನತ ಕೌಶಲ್ಯಗಳು',
      'view_passport': 'ಪಾಸ್‌ಪೋರ್ಟ್ ವೀಕ್ಷಿಸಿ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'community': 'ಸಮುದಾಯ ಪರಿಶೀಲನೆ',
      'state': 'ರಾಜ್ಯ',
      'language': 'ಭಾಷೆ',
      'occupation': 'ಉದ್ಯೋಗ',
      'change_language': 'ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಿ',
      'cancel': 'ರದ್ದುಗೊಳಿಸಿ',
      'verify_peers': 'ಸಹವರ್ತಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
      'leaderboard': 'ಲೀಡರ್‌ಬೋರ್ಡ್',
      'watch': 'ವೀಕ್ಷಿಸಿ',
      'verify': 'ಪರಿಶೀಲಿಸಿ',
      'verifications_done': 'ಪರಿಶೀಲನೆಗಳು ಮುಗಿದಿವೆ',
    },
    'Bengali': {
      'welcome': 'আবার স্বাগতম',
      'dashboard': 'ড্যাশবোর্ড',
      'verify_skills': 'আজ আপনার দক্ষতা যাচাই করতে প্রস্তুত?',
      'start_assessment': 'ভিডিও মূল্যায়ন শুরু করুন',
      'record_work': 'AI দ্বারা অবিলম্বে প্রত্যয়িত হতে আপনার কাজ রেকর্ড করুন',
      'top_skills': 'আমার শীর্ষ দক্ষতা',
      'view_passport': 'পাসপোর্ট দেখুন',
      'profile': 'প্রোফাইল',
      'logout': 'লগ আউট',
      'community': 'সম্প্রদায় যাচাইকরণ',
      'state': 'রাজ্য',
      'language': 'ভাষা',
      'occupation': 'পেশা',
      'change_language': 'ভাষা পরিবর্তন করুন',
      'cancel': 'বাতিল করুন',
      'verify_peers': 'সহকর্মীদের যাচাই করুন',
      'leaderboard': 'লিডারবোর্ড',
      'watch': 'দেখুন',
      'verify': 'যাচাই করুন',
      'verifications_done': 'যাচাইকরণ সম্পন্ন হয়েছে',
    }
  };

  static String get(String key, String language) {
    final langMap = _translations[language] ?? _translations['English']!;
    return langMap[key] ?? _translations['English']![key] ?? key;
  }
}
